$axure.loadCurrentPage({
  "url":"yq_create1.html",
  "generationDate":new Date(1483926311127.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9934540de5d4407acf6d30235e969fe",
    "type":"Axure:Page",
    "name":"yq_create1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b7c91bec3f9147329a648a7167b2e949",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":511}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd60b86f6724c42baf17a90b92f7643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":511}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/yq_xiugai/u0.png"}},
{
          "id":"df72883de9774e77932bd3d14f0529a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"203bcad8d67d4432a6ae2b6be42ee222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c96329dfad234647afea22afb1518e74",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebea92ff3b094aeeb4dbbe2d96100ad9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24c65e4ff3ee4c27a8880254ad7192e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"14f166c5b3d14ce5a3b444778e6fc557",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f32988591664aeba244f8875a6daf4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"c5158a6a38b440e7ab2fd05e46c9284a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208a80e556654619bec593d7bdbe815f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"b850c7da64b3453894ae5124d1292bf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c0985b910c4d2db504f0d6d2267eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9a2a5edaf4a42cea6c97abeccfafac7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":285,
              "y":588},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e29fe95af771476bbd673c4a6aa5a8dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"006e5255dd114a91914470a8dc6ef349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"132c2a6a12cc42fab70bfc26d28a4369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"461153aa33a0487ca6519facf3ff4ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4d0f211544c45e58c5aec3e196a2518",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8cb58bb86aa4ad79f1a84e559737db0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c73a522021492ea186de81e7bf254d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff4003c81d434fd0bd215ba4d2c69f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e5d69a8fe143b5b4226b53eab6b2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5099a1de341a48819bec92210ed08c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"637bf9d27a4e47399252fc3d5bf04aab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":331},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a463eb9d464631940227192e9fca2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":331},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acbf27a4975845dc9e7fb0bf9969c4c4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":356},
            "size":{
              "width":519,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce53f5bf0e644deb410e6fe9bd78e7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cfd66774b4c7495480f5fda9cd429ace",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u27.png"}},
{
              "id":"f6c72075f26b4520a83d064d7bb4b424",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4135e8d97274d8d915e0966609c4488",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"2d2f37dafaca40e497b7440e07771b17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d55e2f0ef2be4ca086b06c2c1595d296",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"eac1b1a94528414ca3a04c4db11ae846",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":374,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a29e2814e1c4bfc81db1a8faede4854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":374,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u33.png"}},
{
              "id":"ed89b6fa7b0b44d0b38c9d244e545ad0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b688425ce1f40bab4a9685c987fd03d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"ea8d79e9a4ab4857943b3bb529ec7887",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d901ef36f5b4796a7b3b1b5e638a52f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"7a0b75b484a14c429a7114d49b694fc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de30a85643134f7a8c59e4a078b45b3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"77e30442e0d240a687abc3846ea9a1c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d23a26c196040ebb07b2c925c4a7eb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"7ec31d6cfa164aa0b83e1fee201c5195",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb814a1bd3314c8a966a5f65c11a47ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"59e683f0082c40b6b42c9f2f41110d35",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":120},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0720b221fe88416b83ab4e420f2dd234",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":120},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"cf1d9b51c6fc4de38b9fdd07dfb34226",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c4fa389565341b38dae6860dbe2235f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"750b9bbaa36349c6a284f53bba67b599",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":150},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30790117e1df48e0ab3fcaa683568279",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":150},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"95d262cb6e934ee3afc33b0c27dce85c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7b9efc4d6624f1f8676f8c25682b16d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u75.png"}},
{
              "id":"e6e01f8311404bc99ca42f333548045b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":180},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36139617b2df4458a1f91d54d640768f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":180},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u81.png"}},
{
              "id":"1d5fc68c6cc84a849065e96cdf3937d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3f4d92a206349afba017d623e934266",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u29.png"}},
{
              "id":"cd0a712b3b5a4a6eb4874f1be70cb8de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bab0209d5a8549fea2abb31b21b74f27",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"63a14c6d60b04107a289a1cba66dd271",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fc227196d2a4c73b5fe977a0c7e8081",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"0a736b5a7440487bb0b83bd85e9a235e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5b8862adfcfe40a096b6e12f8230212d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"d73f7ebec93b4272827c12a96da82a6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":120},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b1a674e97414a2bb8ec30312047aac2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":120},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"28f17a00df004326b18a220f1fafc6b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":150},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b1002a2005445568a72d31e0205af26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":150},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"6f6a64fefdc24baf830a9c3ba16c2218",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":180},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31c9744591fa42a5bfb111835944f89d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":180},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u77.png"}},
{
              "id":"ba5213ec168c4ed5902fd05dae2afa3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":249,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12b41b11d15e440a8a0dd61c6dc11338",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":249,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u31.png"}},
{
              "id":"2a66f9d35fbf415faf3d0d59fd06891c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":30},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1d62ead0b4c4ece9eb700307412ac97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"25a6a44418c0440e87f813f4d85232ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":60},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"adaa94dd368d4e6fa33cd0e686521e15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":60},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"b6eb32b4b60641d1abad844d1ff89459",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":90},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4600181f55542beb0f86db8d83d3b38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"96a042d03fd2438ba140f6909658624a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":120},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6a81aae40c24d5a8dfe4027568b99ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":120},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"e0b0a3b39f5f4470a302ddacce08e9ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":150},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c5d596df73a412b9c797bdfef9bbc7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":150},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"6ae8d0c8c3d34a6caecf3c9ee177f1f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":180},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9beb7dc30ac4a56852e5a65cb1ca127",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":180},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u79.png"}}]},
{
          "id":"193d726b0d8d4194a6d9af73068656c8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":225},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d292e15a438414b993cc14456027030",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":254},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"631fbc294a894244a9e84fd381962bc2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":254},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6f680be2246e4fd59e6106ea31b07f81",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":225},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"69fc2c1cdc0949a081ac9152adb99b76",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4709384f649d4755a6dcccc645058107",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"0a7724d479cd40e98c40a93c57698667",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"a94d58f457a64a8ba7cec03ec9a86189",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"6923c22e80a84296bfcd6bac5e358bd7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"f803a706dbbc42c09ba76fce601c70c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"3ab80a37eaec47e8babf95a0a1ec28a4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"b8b623d5a90a443eac2c6e48346ffb4c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"05e074cbce2e4d568e997ae03ee0e8c7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"b008502b6d4f4cd6b80d9572671ded53",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"9cccd03cb1d94fdba4c406b8a3ea1c72",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"740caf7fe9f54538b8bd1026f02bf5a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"3d4cb377328640238b51c1fa9e7aca61",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b91bffb61bb54d10ab4df8d0006b5ed9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"75ab01ccb9ca40d4a3661db30cba07b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1e4d483bfe41b3813b13869151b6d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76e1d79ffb5c43b784e333e1c11297ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e75bd44782a46b5834b50de6735f404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"074b650f80794959a8b79cc27e386037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5529e6dd4e714ed483bf8300881c3679",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bdd30b9819b4412b24514aecdf10b5f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e374b542090a4f64b0da70a105e5fe2f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4b43c3e03dbb4732a82c8945bc95607e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":254},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e2e8224ced44081ad7649601d3c71e3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":254},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yq_create in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yq_create.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b7c91bec3f9147329a648a7167b2e949":{
      "scriptId":"u0"},
    "5cd60b86f6724c42baf17a90b92f7643":{
      "scriptId":"u1"},
    "df72883de9774e77932bd3d14f0529a6":{
      "scriptId":"u2"},
    "203bcad8d67d4432a6ae2b6be42ee222":{
      "scriptId":"u3"},
    "c96329dfad234647afea22afb1518e74":{
      "scriptId":"u4"},
    "ebea92ff3b094aeeb4dbbe2d96100ad9":{
      "scriptId":"u5"},
    "24c65e4ff3ee4c27a8880254ad7192e6":{
      "scriptId":"u6"},
    "14f166c5b3d14ce5a3b444778e6fc557":{
      "scriptId":"u7"},
    "6f32988591664aeba244f8875a6daf4b":{
      "scriptId":"u8"},
    "c5158a6a38b440e7ab2fd05e46c9284a":{
      "scriptId":"u9"},
    "208a80e556654619bec593d7bdbe815f":{
      "scriptId":"u10"},
    "b850c7da64b3453894ae5124d1292bf7":{
      "scriptId":"u11"},
    "33c0985b910c4d2db504f0d6d2267eb8":{
      "scriptId":"u12"},
    "f9a2a5edaf4a42cea6c97abeccfafac7":{
      "scriptId":"u13"},
    "e29fe95af771476bbd673c4a6aa5a8dd":{
      "scriptId":"u14"},
    "006e5255dd114a91914470a8dc6ef349":{
      "scriptId":"u15"},
    "132c2a6a12cc42fab70bfc26d28a4369":{
      "scriptId":"u16"},
    "461153aa33a0487ca6519facf3ff4ddb":{
      "scriptId":"u17"},
    "a4d0f211544c45e58c5aec3e196a2518":{
      "scriptId":"u18"},
    "a8cb58bb86aa4ad79f1a84e559737db0":{
      "scriptId":"u19"},
    "11c73a522021492ea186de81e7bf254d":{
      "scriptId":"u20"},
    "ff4003c81d434fd0bd215ba4d2c69f63":{
      "scriptId":"u21"},
    "14e5d69a8fe143b5b4226b53eab6b2de":{
      "scriptId":"u22"},
    "5099a1de341a48819bec92210ed08c22":{
      "scriptId":"u23"},
    "637bf9d27a4e47399252fc3d5bf04aab":{
      "scriptId":"u24"},
    "30a463eb9d464631940227192e9fca2c":{
      "scriptId":"u25"},
    "acbf27a4975845dc9e7fb0bf9969c4c4":{
      "scriptId":"u26"},
    "5ce53f5bf0e644deb410e6fe9bd78e7c":{
      "scriptId":"u27"},
    "cfd66774b4c7495480f5fda9cd429ace":{
      "scriptId":"u28"},
    "1d5fc68c6cc84a849065e96cdf3937d8":{
      "scriptId":"u29"},
    "b3f4d92a206349afba017d623e934266":{
      "scriptId":"u30"},
    "ba5213ec168c4ed5902fd05dae2afa3c":{
      "scriptId":"u31"},
    "12b41b11d15e440a8a0dd61c6dc11338":{
      "scriptId":"u32"},
    "eac1b1a94528414ca3a04c4db11ae846":{
      "scriptId":"u33"},
    "1a29e2814e1c4bfc81db1a8faede4854":{
      "scriptId":"u34"},
    "f6c72075f26b4520a83d064d7bb4b424":{
      "scriptId":"u35"},
    "a4135e8d97274d8d915e0966609c4488":{
      "scriptId":"u36"},
    "cd0a712b3b5a4a6eb4874f1be70cb8de":{
      "scriptId":"u37"},
    "bab0209d5a8549fea2abb31b21b74f27":{
      "scriptId":"u38"},
    "2a66f9d35fbf415faf3d0d59fd06891c":{
      "scriptId":"u39"},
    "c1d62ead0b4c4ece9eb700307412ac97":{
      "scriptId":"u40"},
    "ed89b6fa7b0b44d0b38c9d244e545ad0":{
      "scriptId":"u41"},
    "6b688425ce1f40bab4a9685c987fd03d":{
      "scriptId":"u42"},
    "2d2f37dafaca40e497b7440e07771b17":{
      "scriptId":"u43"},
    "d55e2f0ef2be4ca086b06c2c1595d296":{
      "scriptId":"u44"},
    "63a14c6d60b04107a289a1cba66dd271":{
      "scriptId":"u45"},
    "5fc227196d2a4c73b5fe977a0c7e8081":{
      "scriptId":"u46"},
    "25a6a44418c0440e87f813f4d85232ba":{
      "scriptId":"u47"},
    "adaa94dd368d4e6fa33cd0e686521e15":{
      "scriptId":"u48"},
    "ea8d79e9a4ab4857943b3bb529ec7887":{
      "scriptId":"u49"},
    "3d901ef36f5b4796a7b3b1b5e638a52f":{
      "scriptId":"u50"},
    "7a0b75b484a14c429a7114d49b694fc2":{
      "scriptId":"u51"},
    "de30a85643134f7a8c59e4a078b45b3f":{
      "scriptId":"u52"},
    "0a736b5a7440487bb0b83bd85e9a235e":{
      "scriptId":"u53"},
    "5b8862adfcfe40a096b6e12f8230212d":{
      "scriptId":"u54"},
    "b6eb32b4b60641d1abad844d1ff89459":{
      "scriptId":"u55"},
    "e4600181f55542beb0f86db8d83d3b38":{
      "scriptId":"u56"},
    "77e30442e0d240a687abc3846ea9a1c5":{
      "scriptId":"u57"},
    "1d23a26c196040ebb07b2c925c4a7eb1":{
      "scriptId":"u58"},
    "7ec31d6cfa164aa0b83e1fee201c5195":{
      "scriptId":"u59"},
    "eb814a1bd3314c8a966a5f65c11a47ee":{
      "scriptId":"u60"},
    "d73f7ebec93b4272827c12a96da82a6f":{
      "scriptId":"u61"},
    "4b1a674e97414a2bb8ec30312047aac2":{
      "scriptId":"u62"},
    "96a042d03fd2438ba140f6909658624a":{
      "scriptId":"u63"},
    "d6a81aae40c24d5a8dfe4027568b99ac":{
      "scriptId":"u64"},
    "59e683f0082c40b6b42c9f2f41110d35":{
      "scriptId":"u65"},
    "0720b221fe88416b83ab4e420f2dd234":{
      "scriptId":"u66"},
    "cf1d9b51c6fc4de38b9fdd07dfb34226":{
      "scriptId":"u67"},
    "8c4fa389565341b38dae6860dbe2235f":{
      "scriptId":"u68"},
    "28f17a00df004326b18a220f1fafc6b4":{
      "scriptId":"u69"},
    "2b1002a2005445568a72d31e0205af26":{
      "scriptId":"u70"},
    "e0b0a3b39f5f4470a302ddacce08e9ca":{
      "scriptId":"u71"},
    "7c5d596df73a412b9c797bdfef9bbc7e":{
      "scriptId":"u72"},
    "750b9bbaa36349c6a284f53bba67b599":{
      "scriptId":"u73"},
    "30790117e1df48e0ab3fcaa683568279":{
      "scriptId":"u74"},
    "95d262cb6e934ee3afc33b0c27dce85c":{
      "scriptId":"u75"},
    "c7b9efc4d6624f1f8676f8c25682b16d":{
      "scriptId":"u76"},
    "6f6a64fefdc24baf830a9c3ba16c2218":{
      "scriptId":"u77"},
    "31c9744591fa42a5bfb111835944f89d":{
      "scriptId":"u78"},
    "6ae8d0c8c3d34a6caecf3c9ee177f1f5":{
      "scriptId":"u79"},
    "a9beb7dc30ac4a56852e5a65cb1ca127":{
      "scriptId":"u80"},
    "e6e01f8311404bc99ca42f333548045b":{
      "scriptId":"u81"},
    "36139617b2df4458a1f91d54d640768f":{
      "scriptId":"u82"},
    "193d726b0d8d4194a6d9af73068656c8":{
      "scriptId":"u83"},
    "4d292e15a438414b993cc14456027030":{
      "scriptId":"u84"},
    "631fbc294a894244a9e84fd381962bc2":{
      "scriptId":"u85"},
    "6f680be2246e4fd59e6106ea31b07f81":{
      "scriptId":"u86"},
    "69fc2c1cdc0949a081ac9152adb99b76":{
      "scriptId":"u87"},
    "4709384f649d4755a6dcccc645058107":{
      "scriptId":"u88"},
    "0a7724d479cd40e98c40a93c57698667":{
      "scriptId":"u89"},
    "a94d58f457a64a8ba7cec03ec9a86189":{
      "scriptId":"u90"},
    "6923c22e80a84296bfcd6bac5e358bd7":{
      "scriptId":"u91"},
    "f803a706dbbc42c09ba76fce601c70c3":{
      "scriptId":"u92"},
    "3ab80a37eaec47e8babf95a0a1ec28a4":{
      "scriptId":"u93"},
    "b8b623d5a90a443eac2c6e48346ffb4c":{
      "scriptId":"u94"},
    "05e074cbce2e4d568e997ae03ee0e8c7":{
      "scriptId":"u95"},
    "b008502b6d4f4cd6b80d9572671ded53":{
      "scriptId":"u96"},
    "9cccd03cb1d94fdba4c406b8a3ea1c72":{
      "scriptId":"u97"},
    "740caf7fe9f54538b8bd1026f02bf5a0":{
      "scriptId":"u98"},
    "3d4cb377328640238b51c1fa9e7aca61":{
      "scriptId":"u99"},
    "b91bffb61bb54d10ab4df8d0006b5ed9":{
      "scriptId":"u100"},
    "75ab01ccb9ca40d4a3661db30cba07b8":{
      "scriptId":"u101"},
    "5f1e4d483bfe41b3813b13869151b6d3":{
      "scriptId":"u102"},
    "76e1d79ffb5c43b784e333e1c11297ac":{
      "scriptId":"u103"},
    "3e75bd44782a46b5834b50de6735f404":{
      "scriptId":"u104"},
    "074b650f80794959a8b79cc27e386037":{
      "scriptId":"u105"},
    "5529e6dd4e714ed483bf8300881c3679":{
      "scriptId":"u106"},
    "5bdd30b9819b4412b24514aecdf10b5f":{
      "scriptId":"u107"},
    "e374b542090a4f64b0da70a105e5fe2f":{
      "scriptId":"u108"},
    "4b43c3e03dbb4732a82c8945bc95607e":{
      "scriptId":"u109"},
    "2e2e8224ced44081ad7649601d3c71e3":{
      "scriptId":"u110"}}});