$axure.loadCurrentPage({
  "url":"jia.html",
  "generationDate":new Date(1483926309065.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4cbf90745ed7441293bc5e181bafa31c",
    "type":"Axure:Page",
    "name":"jia",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9ff83a678dd4d988b5464544f76b2b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90773e88e1eb4b9f8b14e53702ab1d32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u0.png"}},
{
          "id":"a5ebaa73cac94b208b70a14c0f51e245",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e47e3dec2134b46968b193fc4aed3db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dadab3e3a12b4217948e688415e2a031",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":192},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c8f06843cb74b1ba9795e828471451c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83a4f0909a814f7e8a8aca119bddcea6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"d3e6d5da86704feb880875a9f77dd852",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee528bacb8d34463a7595bc0d7631e3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"b8491eda285840679b8fe5d37af40632",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bbc410607ea440f96c9a9aef24515e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"0b97d722c8254ef682d60e45f2e671bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3fec25fdc241c699806bb04b531dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a4dbc56a77c487594156981b018e8b7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":390},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9d925e976bff4a0d8c5e1ad399976698",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba5d71c495504f1c888ec44687b484df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4766449ce0ea41d58adf13bbf1259607",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53a87fa1f0744a0c99e3b119c7c09465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f288a534b5734be993386d877b55eaf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bd095682e0748bd90ad6d453a5f6989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0b59a021329487fb2f9dde5f8868cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124e7c372d474dbabfcda95092af1f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa450c9c5ee64efd8683c55584ff350d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7d4cacb26143ee826ed8458075ceef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4ebd8fba4284f1380b3b9a8f7a8e0e1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7826a4236082438da4cd3be37fca94ee",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f78c859a8e5d440f9b0b252534b3bc47",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":225},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"f98035901f254aa0a867e801706ab853",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c288788e75b3480c85a390ea083db656",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"0887c3dee0ae4be1a5db102d86fa9337",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"e692e0c98f1443478a6ab989f18baedd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dd1c854923994fba97b0ae8a1845d97b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":252},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"7d0a1a1eaf234efc9157ea5543ccbe81",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dae84c80685d4e16acdd152ab61510e9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"6642c3593436499886990340ccbfd634",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"81da9e984f694b179e682895d963c712",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dbda021420f8402192cb1ca2064981c5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":280},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"a04296262ce44f6b95a6458df20c59a8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"eee84595895b4725b390abaad7a5b9b4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"7745d32f9617413d9bb0170512de0a14",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"1da9d2efd93448ae9d50568197027a29",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"47937d1d4ed0452ebc2c65719915cb4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19d49b3f90f491f9884017e47ded4f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe94aa2b88e9436abc6967a77320195a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9685162616f741c98646692c4a2c1987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab1279daa3ef4d0abd57002d7e3446ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177b05f36bcb413a8d9e2117c21d70ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5a994792b5491bb1c9102006acc942",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0d02e251d30a411a85788e3fa889ece1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"62f6da398dfa4dd08457d66ec2724b74",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1565e845e6e2441db3ccb9fa5c36ceeb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b80a97ec51f44be5b89e1bb21f648981",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1f03343bf73b4dacaff0eb41a81e0cbc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d2837097d40d44ca8ac2ba455cffcaf4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":306},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"61ab0d69bd1f461fb153f114ba5ddbe7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":307},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1062420818484ffc9d5e8bd370e85c85",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":306},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"1dfd709ce0204ff1b1af6fec3cb95e47",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":306},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"c317283c5f20480888e1ea01b37604e9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":307},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"006f4822903a4af4ad97624c969226f2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":305},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6a6261d4939c4c87b6ba24a6008ce7b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":305},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hg_xiugai in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hg_xiugai.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "d9ff83a678dd4d988b5464544f76b2b4":{
      "scriptId":"u0"},
    "90773e88e1eb4b9f8b14e53702ab1d32":{
      "scriptId":"u1"},
    "a5ebaa73cac94b208b70a14c0f51e245":{
      "scriptId":"u2"},
    "6e47e3dec2134b46968b193fc4aed3db":{
      "scriptId":"u3"},
    "dadab3e3a12b4217948e688415e2a031":{
      "scriptId":"u4"},
    "7c8f06843cb74b1ba9795e828471451c":{
      "scriptId":"u5"},
    "83a4f0909a814f7e8a8aca119bddcea6":{
      "scriptId":"u6"},
    "d3e6d5da86704feb880875a9f77dd852":{
      "scriptId":"u7"},
    "ee528bacb8d34463a7595bc0d7631e3e":{
      "scriptId":"u8"},
    "b8491eda285840679b8fe5d37af40632":{
      "scriptId":"u9"},
    "7bbc410607ea440f96c9a9aef24515e6":{
      "scriptId":"u10"},
    "0b97d722c8254ef682d60e45f2e671bb":{
      "scriptId":"u11"},
    "8a3fec25fdc241c699806bb04b531dd5":{
      "scriptId":"u12"},
    "8a4dbc56a77c487594156981b018e8b7":{
      "scriptId":"u13"},
    "9d925e976bff4a0d8c5e1ad399976698":{
      "scriptId":"u14"},
    "ba5d71c495504f1c888ec44687b484df":{
      "scriptId":"u15"},
    "4766449ce0ea41d58adf13bbf1259607":{
      "scriptId":"u16"},
    "53a87fa1f0744a0c99e3b119c7c09465":{
      "scriptId":"u17"},
    "f288a534b5734be993386d877b55eaf4":{
      "scriptId":"u18"},
    "8bd095682e0748bd90ad6d453a5f6989":{
      "scriptId":"u19"},
    "f0b59a021329487fb2f9dde5f8868cbf":{
      "scriptId":"u20"},
    "124e7c372d474dbabfcda95092af1f45":{
      "scriptId":"u21"},
    "aa450c9c5ee64efd8683c55584ff350d":{
      "scriptId":"u22"},
    "ef7d4cacb26143ee826ed8458075ceef":{
      "scriptId":"u23"},
    "f4ebd8fba4284f1380b3b9a8f7a8e0e1":{
      "scriptId":"u24"},
    "7826a4236082438da4cd3be37fca94ee":{
      "scriptId":"u25"},
    "f78c859a8e5d440f9b0b252534b3bc47":{
      "scriptId":"u26"},
    "f98035901f254aa0a867e801706ab853":{
      "scriptId":"u27"},
    "c288788e75b3480c85a390ea083db656":{
      "scriptId":"u28"},
    "0887c3dee0ae4be1a5db102d86fa9337":{
      "scriptId":"u29"},
    "e692e0c98f1443478a6ab989f18baedd":{
      "scriptId":"u30"},
    "dd1c854923994fba97b0ae8a1845d97b":{
      "scriptId":"u31"},
    "7d0a1a1eaf234efc9157ea5543ccbe81":{
      "scriptId":"u32"},
    "dae84c80685d4e16acdd152ab61510e9":{
      "scriptId":"u33"},
    "6642c3593436499886990340ccbfd634":{
      "scriptId":"u34"},
    "81da9e984f694b179e682895d963c712":{
      "scriptId":"u35"},
    "dbda021420f8402192cb1ca2064981c5":{
      "scriptId":"u36"},
    "a04296262ce44f6b95a6458df20c59a8":{
      "scriptId":"u37"},
    "eee84595895b4725b390abaad7a5b9b4":{
      "scriptId":"u38"},
    "7745d32f9617413d9bb0170512de0a14":{
      "scriptId":"u39"},
    "1da9d2efd93448ae9d50568197027a29":{
      "scriptId":"u40"},
    "47937d1d4ed0452ebc2c65719915cb4e":{
      "scriptId":"u41"},
    "e19d49b3f90f491f9884017e47ded4f1":{
      "scriptId":"u42"},
    "fe94aa2b88e9436abc6967a77320195a":{
      "scriptId":"u43"},
    "9685162616f741c98646692c4a2c1987":{
      "scriptId":"u44"},
    "ab1279daa3ef4d0abd57002d7e3446ba":{
      "scriptId":"u45"},
    "177b05f36bcb413a8d9e2117c21d70ff":{
      "scriptId":"u46"},
    "1f5a994792b5491bb1c9102006acc942":{
      "scriptId":"u47"},
    "0d02e251d30a411a85788e3fa889ece1":{
      "scriptId":"u48"},
    "62f6da398dfa4dd08457d66ec2724b74":{
      "scriptId":"u49"},
    "1565e845e6e2441db3ccb9fa5c36ceeb":{
      "scriptId":"u50"},
    "b80a97ec51f44be5b89e1bb21f648981":{
      "scriptId":"u51"},
    "1f03343bf73b4dacaff0eb41a81e0cbc":{
      "scriptId":"u52"},
    "d2837097d40d44ca8ac2ba455cffcaf4":{
      "scriptId":"u53"},
    "61ab0d69bd1f461fb153f114ba5ddbe7":{
      "scriptId":"u54"},
    "1062420818484ffc9d5e8bd370e85c85":{
      "scriptId":"u55"},
    "1dfd709ce0204ff1b1af6fec3cb95e47":{
      "scriptId":"u56"},
    "c317283c5f20480888e1ea01b37604e9":{
      "scriptId":"u57"},
    "006f4822903a4af4ad97624c969226f2":{
      "scriptId":"u58"},
    "6a6261d4939c4c87b6ba24a6008ce7b1":{
      "scriptId":"u59"}}});