$axure.loadCurrentPage({
  "url":"jt_xiugai.html",
  "generationDate":new Date(1483926311290.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a5cc40c80c2c4164a8b1a8c05600a630",
    "type":"Axure:Page",
    "name":"jt_xiugai",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"96b887ab11d4442fbd07f687c9786d9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5ea6ea462148fab16ac35cb1d965c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u0.png"}},
{
          "id":"7e620f7dd9624933b7034c11700c8423",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a24a2277fbb24803bc1f1ff6eee2637d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d648e0ecae17476981730f85b6afbaec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98852c8e5272407c933635faca441ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"5f609562515d409f9a4173bb40132b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4191d93116540c3b0fe894e925cb0a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58c489863fcc4493bf3b29a4ec65a013",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3560681e27d94a6b8d9b36ab312fda88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90e20617bc324b6aa5d2a78724335521",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157c3e524e314cfebb50da4d44b3381c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"275de63ad6d64986ad312221b308b0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2caadab2219404799099cc7062fe673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"547ea0c4a1dd4361a331fac8f7cd81cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efdbb4a2fc6e4454b702abbb37891bf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b14d17e1d9f46b89cf79d752941bad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dcaff2afe8f4dfcabac831f6dc7d34e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"594b6af76bc24167a825198f7eee163a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":192},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"425596a9469a498cbce5bf184a48456a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e06efa6ae90b47e5b445ec1c58d9844a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"ff84c72e67564cc090c602c0ba9471e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e69f2c24e14a40aeb5d5af4f8204f18e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"1f48e2b711f74ad4b1973ae4cb72cace",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":390},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a2452dac437e49ba8de1e16f2a41bc04",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f096a0f78aa543ac95682c2258666147",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b56e2049594f4a438f07c6986fe38068",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":225},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"f4b2147725534ae6bea7c3b8fe23604a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7b955c6381ce469392d2382f040926a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"a82c64a0b0d94a3ca725a7b33385295b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"fcbf5fa2d2f04fe2b548e046c0dddac4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"459dcfa3e255453dac36d4601ecb9963",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":252},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"8a90d8d1fe6d4e48a2f7004482eb0c3c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d40ed80c84e14945abf64562fa1207c7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"481983bf53a54d2d9f4d4e75b61d429a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"22f0151ebb6945668f39b83206228f73",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ee2ac22ebadc48638e6b7f3228d7c9ea",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":280},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"b161b186f82e4d9783e9789ccb422473",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fca18b2c4384401fa8e8f4952809bf04",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"d56fa0b6ebef4fbabe36866c5eb155a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"7cba6ba042074254b8d67c4a75bf6289",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"79404e5507fe4aa5ac98734844a1baad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcfe1931673845a09a2b94445de31259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78924be5126c44f5a1395e86351523d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8344502f88cf468ea5b5befbe7880228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b17f46eeb43046a5b4bc6058f1d98572",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2045b9226884299a6ad89286fc03b7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b3ff6eb8b3f407fba5da4c94f4b2ad8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6eec08c51ca4ca5adc4891f9792a368",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c97183724c2a4ba19902898578cda854",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"42df84f765c74e9aa7d644b8a73a455e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"564cfb5643e648c9b78c0cc9e09ae31c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jia in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jia_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"08a4ae35cec343acb026e9d8bcc6ec05",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jian in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jian_4.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "96b887ab11d4442fbd07f687c9786d9e":{
      "scriptId":"u0"},
    "3a5ea6ea462148fab16ac35cb1d965c5":{
      "scriptId":"u1"},
    "7e620f7dd9624933b7034c11700c8423":{
      "scriptId":"u2"},
    "a24a2277fbb24803bc1f1ff6eee2637d":{
      "scriptId":"u3"},
    "d648e0ecae17476981730f85b6afbaec":{
      "scriptId":"u4"},
    "98852c8e5272407c933635faca441ac6":{
      "scriptId":"u5"},
    "5f609562515d409f9a4173bb40132b85":{
      "scriptId":"u6"},
    "d4191d93116540c3b0fe894e925cb0a9":{
      "scriptId":"u7"},
    "58c489863fcc4493bf3b29a4ec65a013":{
      "scriptId":"u8"},
    "3560681e27d94a6b8d9b36ab312fda88":{
      "scriptId":"u9"},
    "90e20617bc324b6aa5d2a78724335521":{
      "scriptId":"u10"},
    "157c3e524e314cfebb50da4d44b3381c":{
      "scriptId":"u11"},
    "275de63ad6d64986ad312221b308b0cf":{
      "scriptId":"u12"},
    "c2caadab2219404799099cc7062fe673":{
      "scriptId":"u13"},
    "547ea0c4a1dd4361a331fac8f7cd81cc":{
      "scriptId":"u14"},
    "efdbb4a2fc6e4454b702abbb37891bf2":{
      "scriptId":"u15"},
    "8b14d17e1d9f46b89cf79d752941bad3":{
      "scriptId":"u16"},
    "2dcaff2afe8f4dfcabac831f6dc7d34e":{
      "scriptId":"u17"},
    "594b6af76bc24167a825198f7eee163a":{
      "scriptId":"u18"},
    "425596a9469a498cbce5bf184a48456a":{
      "scriptId":"u19"},
    "e06efa6ae90b47e5b445ec1c58d9844a":{
      "scriptId":"u20"},
    "ff84c72e67564cc090c602c0ba9471e9":{
      "scriptId":"u21"},
    "e69f2c24e14a40aeb5d5af4f8204f18e":{
      "scriptId":"u22"},
    "1f48e2b711f74ad4b1973ae4cb72cace":{
      "scriptId":"u23"},
    "a2452dac437e49ba8de1e16f2a41bc04":{
      "scriptId":"u24"},
    "f096a0f78aa543ac95682c2258666147":{
      "scriptId":"u25"},
    "b56e2049594f4a438f07c6986fe38068":{
      "scriptId":"u26"},
    "f4b2147725534ae6bea7c3b8fe23604a":{
      "scriptId":"u27"},
    "7b955c6381ce469392d2382f040926a6":{
      "scriptId":"u28"},
    "a82c64a0b0d94a3ca725a7b33385295b":{
      "scriptId":"u29"},
    "fcbf5fa2d2f04fe2b548e046c0dddac4":{
      "scriptId":"u30"},
    "459dcfa3e255453dac36d4601ecb9963":{
      "scriptId":"u31"},
    "8a90d8d1fe6d4e48a2f7004482eb0c3c":{
      "scriptId":"u32"},
    "d40ed80c84e14945abf64562fa1207c7":{
      "scriptId":"u33"},
    "481983bf53a54d2d9f4d4e75b61d429a":{
      "scriptId":"u34"},
    "22f0151ebb6945668f39b83206228f73":{
      "scriptId":"u35"},
    "ee2ac22ebadc48638e6b7f3228d7c9ea":{
      "scriptId":"u36"},
    "b161b186f82e4d9783e9789ccb422473":{
      "scriptId":"u37"},
    "fca18b2c4384401fa8e8f4952809bf04":{
      "scriptId":"u38"},
    "d56fa0b6ebef4fbabe36866c5eb155a0":{
      "scriptId":"u39"},
    "7cba6ba042074254b8d67c4a75bf6289":{
      "scriptId":"u40"},
    "79404e5507fe4aa5ac98734844a1baad":{
      "scriptId":"u41"},
    "fcfe1931673845a09a2b94445de31259":{
      "scriptId":"u42"},
    "78924be5126c44f5a1395e86351523d3":{
      "scriptId":"u43"},
    "8344502f88cf468ea5b5befbe7880228":{
      "scriptId":"u44"},
    "b17f46eeb43046a5b4bc6058f1d98572":{
      "scriptId":"u45"},
    "f2045b9226884299a6ad89286fc03b7f":{
      "scriptId":"u46"},
    "6b3ff6eb8b3f407fba5da4c94f4b2ad8":{
      "scriptId":"u47"},
    "b6eec08c51ca4ca5adc4891f9792a368":{
      "scriptId":"u48"},
    "c97183724c2a4ba19902898578cda854":{
      "scriptId":"u49"},
    "42df84f765c74e9aa7d644b8a73a455e":{
      "scriptId":"u50"},
    "564cfb5643e648c9b78c0cc9e09ae31c":{
      "scriptId":"u51"},
    "08a4ae35cec343acb026e9d8bcc6ec05":{
      "scriptId":"u52"}}});