$axure.loadCurrentPage({
  "url":"jia_3.html",
  "generationDate":new Date(1483926310676.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d173a0fd296442997cecd35243095ce",
    "type":"Axure:Page",
    "name":"jia",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ae18f7c08e39455da658699b6f257e0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":511}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"838cdf61a87542d085dcfae6d07e8087",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":511}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/yq_xiugai/u0.png"}},
{
          "id":"3c0ae841160142a0bd4fce84de3b2b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df33a58811e4472a1e1a2f534f33a7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14de061157d14a44b8435e48ab99c887",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0c10e6efef54ec791395d5d1f639933",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e820fe6f7c04be584120ab9b44bd873",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"4e660c39d26343ef9a6e50c6cfc4b418",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4005caa3d124e27b801b3e286ae3969",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"3a181a5419ff41a6bcd6f39d229e5827",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29dab4edfe624d3683360f168c907967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"3b7aea79c6de4230abc56d6bb47327a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa73a0a80b7149d7ad071367262a6a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f385a368206f4000851d38dcb3d04e24",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":285,
              "y":588},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1dcf732a911a4b3c841c93c86bb1f020",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ce4622f100a4e4d96e2a9a1e267d37e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b92e57a457ad4f39b10c4f351b30c3c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d99aea6bb02408c9b59c7f2877b8135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a58783407e204aab8bda9f613b01eb44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e925ef29d520450b8f8cd4ec36451e7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d25b0f040aa490cabf662c098dc1e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9edab2a416f445fc8d3811d8d5a71159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2b295b6c31a4fe48804ce2da76f8a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ecb6d4c19741bab42cdfc641b6d293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b63fe049fc7645fe93e979dc5fd59733",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":331},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95323efa947451b8b04affe127e9772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":331},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"050120246d6342a8badf3e4daa39537f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":356},
            "size":{
              "width":519,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b38b64a68da43b7aae7bb32487207a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a8876a0731e4758a0540a3725cdc914",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u27.png"}},
{
              "id":"e06a6a44da794d0ab6d798c41a320fcc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4370c2096ec64d69af8948a961064393",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"f673fc26ebec46e3b9b4fac9c8d8ded3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd474598319f4bcf908969c3687bb8f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"4e6ab4012cdc4c8698849fcae30d8b45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":374,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"777d2699dec640e0978f84d4ef74e804",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":374,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u33.png"}},
{
              "id":"a85f870c208944e48607d3d2bc4e4bd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46e2a1bcc2cf4c3cb2f8714734b8726d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"77a9e85f011e4f3dbd5ffeaaab4ccd0c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"514e6e10dd1a47ed886bae410700f829",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"1c18ad8974ad4abf80f7d5fb61bd69a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99de1888469847008f09e095181dd5f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"a7d23d637b0f425fa2c7b010dee82e46",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bbd0ed54d1041ba8ec68cd54dcb78c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"6139906ddd8540a7b63fa0dde95df5c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fd0038be5e7495db93fb85709f46477",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"cc0aea0ca9cb4f7cac840d13f66a1a3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":120},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05a6174e747a43daa86c4ec81a418e22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":120},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"cee4dce2ffe544c3868d5f7247572637",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acf53af237444d91b9aa29ec1e12de72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"9c87b1ee38d04db19df902a8ec6c2ac6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":150},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e93d7ec3b58f4f8db3b7b88a8456fff9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":150},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"d59aec8005bb4fa9ace5a3f9afbf38d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0fd6b234b1054ebe9c9175af93f67ad9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u75.png"}},
{
              "id":"887d66d46c0e49f7817302383d080f17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":180},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5750ee400134531a58c7d72b0fd6ae9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":180},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u81.png"}},
{
              "id":"3278526451ef4b59b900182dadc425eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1d45d117207e4be3bcd5df3e0d9ef275",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u29.png"}},
{
              "id":"90343d78626b4b2e9d07c556ee81fe61",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41761d3608054a86974ae1db99c99980",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"15b9175123f245469af71642870e5c00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"efb54057460544fd9b2043a3129e565d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"bbb955c07f8843e784ecf69eebd2edfa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6462a9789c3241299a4ec4f6ccc22f39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"cb54e553bd234a70adbfd7e563bb9a1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":120},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6d2be3f4eb742bc807520cc7c137437",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":120},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"6b2f0d19308f403e8000b2efaedadd03",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":150},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e25f27b64df448a8bb09a56877fbf23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":150},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"55e6edb1b1bc461db891a411069e9478",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":180},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df830a4b208e47ef8d4ee952561ae653",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":180},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u77.png"}},
{
              "id":"02e2808de82048f2bc5cc71f2b46dc9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":249,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"795bb16052ae49c2be54a79b7d34c68f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":249,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u31.png"}},
{
              "id":"87b068ca65e24401ab4f8cd580f4f9b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":30},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b99957fa44284898add79dece0e4f625",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"50207054f5ca4f8b9fc781da491259d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":60},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99f5aa2024f3424dad71a121f75cf10f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":60},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"7893baac16de4e6dbe6ad464b1bf0195",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":90},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a72c703816f64f5a83f4207329147112",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"e9b20314918e4d18a1be703511fdea99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":120},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4f9c6b26d644861950550c14129494d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":120},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"611e0af288ea4bf5baeb844b9a69ebf2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":150},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e34be045dd2148afa44e8881f47eb6b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":150},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"67412267a2ce46ffb6876b53a00dd7ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":180},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a7fe4324a534aac9e1a52799011e3cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":180},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u79.png"}}]},
{
          "id":"c9cd48e402fb4f45940ef28c85676ab3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":225},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0206c37d097b4d6d905cd36235a1962d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":255},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"79a39658337146c3a9a2cee5fb276be7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":255},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6d9d7c00cfd442759e54bce293c07bce",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":225},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"76265bb436cf49acbacbc4d0dbe4fd26",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"36c3dda28aa84610b46ec4c1ef7ea9cc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"c736fb29be55454fa2742f0945276f10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4158df36891e4203b571b9e6d798b2f0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"d5b8067f59824faaa9fbdc99d4a567b0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"200827577aa942d78c0b361396310b2a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"1b1961bd4fa34224b72709ca9bad1097",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"d7edaa2cc1b64c3ab17f3754edc16c9e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"20dc5f3c602545c5b2e1e37fee6ed289",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"3aac8601310a4f718f293f07eab0b2f0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"85626b7735ba402fb7431cd0a1320f61",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"c09b31d0c09c45ab9e842f58e5eac3fe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"166b20953d4f490781b2d09f37fd7a84",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6110328520304372a1ed9e4af1d35805",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c78ee52a5f8a4825bf68780d1862453a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fd50675e422444f938065a8a24bd437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"146ffecf1e5d4d509826e4a1ac3d9e44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45ef4ca6727c475292730aad16fbf732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"398125eeb85b4afc9f4fcdced14d3b9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2490932cdbf44ab836d1afcb00960f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c90453d5d5ad48c7bb24f24e5ba101cb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"70cf766002b7405fb4d7358f0f4e783e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a737b1b13d6b43568522d2f821b0944d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":253},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc0b5950bc5e46f3863851b3ae54c3ed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":253},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a063dcc4911442d39ec60c72a575125d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":284},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"99ec54775d4546b4ae098e51d9e72404",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":284},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a1fc21e9542a4d4a8674063ce8c1aa2b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":282},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"99718426052f41cd9d2a3073508392ef",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":282},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yq_xiugai in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yq_xiugai.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ae18f7c08e39455da658699b6f257e0e":{
      "scriptId":"u0"},
    "838cdf61a87542d085dcfae6d07e8087":{
      "scriptId":"u1"},
    "3c0ae841160142a0bd4fce84de3b2b20":{
      "scriptId":"u2"},
    "8df33a58811e4472a1e1a2f534f33a7b":{
      "scriptId":"u3"},
    "14de061157d14a44b8435e48ab99c887":{
      "scriptId":"u4"},
    "c0c10e6efef54ec791395d5d1f639933":{
      "scriptId":"u5"},
    "0e820fe6f7c04be584120ab9b44bd873":{
      "scriptId":"u6"},
    "4e660c39d26343ef9a6e50c6cfc4b418":{
      "scriptId":"u7"},
    "d4005caa3d124e27b801b3e286ae3969":{
      "scriptId":"u8"},
    "3a181a5419ff41a6bcd6f39d229e5827":{
      "scriptId":"u9"},
    "29dab4edfe624d3683360f168c907967":{
      "scriptId":"u10"},
    "3b7aea79c6de4230abc56d6bb47327a6":{
      "scriptId":"u11"},
    "aa73a0a80b7149d7ad071367262a6a1e":{
      "scriptId":"u12"},
    "f385a368206f4000851d38dcb3d04e24":{
      "scriptId":"u13"},
    "1dcf732a911a4b3c841c93c86bb1f020":{
      "scriptId":"u14"},
    "5ce4622f100a4e4d96e2a9a1e267d37e":{
      "scriptId":"u15"},
    "b92e57a457ad4f39b10c4f351b30c3c2":{
      "scriptId":"u16"},
    "5d99aea6bb02408c9b59c7f2877b8135":{
      "scriptId":"u17"},
    "a58783407e204aab8bda9f613b01eb44":{
      "scriptId":"u18"},
    "e925ef29d520450b8f8cd4ec36451e7e":{
      "scriptId":"u19"},
    "1d25b0f040aa490cabf662c098dc1e43":{
      "scriptId":"u20"},
    "9edab2a416f445fc8d3811d8d5a71159":{
      "scriptId":"u21"},
    "e2b295b6c31a4fe48804ce2da76f8a62":{
      "scriptId":"u22"},
    "d5ecb6d4c19741bab42cdfc641b6d293":{
      "scriptId":"u23"},
    "b63fe049fc7645fe93e979dc5fd59733":{
      "scriptId":"u24"},
    "f95323efa947451b8b04affe127e9772":{
      "scriptId":"u25"},
    "050120246d6342a8badf3e4daa39537f":{
      "scriptId":"u26"},
    "3b38b64a68da43b7aae7bb32487207a6":{
      "scriptId":"u27"},
    "7a8876a0731e4758a0540a3725cdc914":{
      "scriptId":"u28"},
    "3278526451ef4b59b900182dadc425eb":{
      "scriptId":"u29"},
    "1d45d117207e4be3bcd5df3e0d9ef275":{
      "scriptId":"u30"},
    "02e2808de82048f2bc5cc71f2b46dc9b":{
      "scriptId":"u31"},
    "795bb16052ae49c2be54a79b7d34c68f":{
      "scriptId":"u32"},
    "4e6ab4012cdc4c8698849fcae30d8b45":{
      "scriptId":"u33"},
    "777d2699dec640e0978f84d4ef74e804":{
      "scriptId":"u34"},
    "e06a6a44da794d0ab6d798c41a320fcc":{
      "scriptId":"u35"},
    "4370c2096ec64d69af8948a961064393":{
      "scriptId":"u36"},
    "90343d78626b4b2e9d07c556ee81fe61":{
      "scriptId":"u37"},
    "41761d3608054a86974ae1db99c99980":{
      "scriptId":"u38"},
    "87b068ca65e24401ab4f8cd580f4f9b3":{
      "scriptId":"u39"},
    "b99957fa44284898add79dece0e4f625":{
      "scriptId":"u40"},
    "a85f870c208944e48607d3d2bc4e4bd8":{
      "scriptId":"u41"},
    "46e2a1bcc2cf4c3cb2f8714734b8726d":{
      "scriptId":"u42"},
    "f673fc26ebec46e3b9b4fac9c8d8ded3":{
      "scriptId":"u43"},
    "dd474598319f4bcf908969c3687bb8f2":{
      "scriptId":"u44"},
    "15b9175123f245469af71642870e5c00":{
      "scriptId":"u45"},
    "efb54057460544fd9b2043a3129e565d":{
      "scriptId":"u46"},
    "50207054f5ca4f8b9fc781da491259d4":{
      "scriptId":"u47"},
    "99f5aa2024f3424dad71a121f75cf10f":{
      "scriptId":"u48"},
    "77a9e85f011e4f3dbd5ffeaaab4ccd0c":{
      "scriptId":"u49"},
    "514e6e10dd1a47ed886bae410700f829":{
      "scriptId":"u50"},
    "1c18ad8974ad4abf80f7d5fb61bd69a9":{
      "scriptId":"u51"},
    "99de1888469847008f09e095181dd5f6":{
      "scriptId":"u52"},
    "bbb955c07f8843e784ecf69eebd2edfa":{
      "scriptId":"u53"},
    "6462a9789c3241299a4ec4f6ccc22f39":{
      "scriptId":"u54"},
    "7893baac16de4e6dbe6ad464b1bf0195":{
      "scriptId":"u55"},
    "a72c703816f64f5a83f4207329147112":{
      "scriptId":"u56"},
    "a7d23d637b0f425fa2c7b010dee82e46":{
      "scriptId":"u57"},
    "8bbd0ed54d1041ba8ec68cd54dcb78c8":{
      "scriptId":"u58"},
    "6139906ddd8540a7b63fa0dde95df5c9":{
      "scriptId":"u59"},
    "4fd0038be5e7495db93fb85709f46477":{
      "scriptId":"u60"},
    "cb54e553bd234a70adbfd7e563bb9a1b":{
      "scriptId":"u61"},
    "a6d2be3f4eb742bc807520cc7c137437":{
      "scriptId":"u62"},
    "e9b20314918e4d18a1be703511fdea99":{
      "scriptId":"u63"},
    "b4f9c6b26d644861950550c14129494d":{
      "scriptId":"u64"},
    "cc0aea0ca9cb4f7cac840d13f66a1a3b":{
      "scriptId":"u65"},
    "05a6174e747a43daa86c4ec81a418e22":{
      "scriptId":"u66"},
    "cee4dce2ffe544c3868d5f7247572637":{
      "scriptId":"u67"},
    "acf53af237444d91b9aa29ec1e12de72":{
      "scriptId":"u68"},
    "6b2f0d19308f403e8000b2efaedadd03":{
      "scriptId":"u69"},
    "6e25f27b64df448a8bb09a56877fbf23":{
      "scriptId":"u70"},
    "611e0af288ea4bf5baeb844b9a69ebf2":{
      "scriptId":"u71"},
    "e34be045dd2148afa44e8881f47eb6b3":{
      "scriptId":"u72"},
    "9c87b1ee38d04db19df902a8ec6c2ac6":{
      "scriptId":"u73"},
    "e93d7ec3b58f4f8db3b7b88a8456fff9":{
      "scriptId":"u74"},
    "d59aec8005bb4fa9ace5a3f9afbf38d3":{
      "scriptId":"u75"},
    "0fd6b234b1054ebe9c9175af93f67ad9":{
      "scriptId":"u76"},
    "55e6edb1b1bc461db891a411069e9478":{
      "scriptId":"u77"},
    "df830a4b208e47ef8d4ee952561ae653":{
      "scriptId":"u78"},
    "67412267a2ce46ffb6876b53a00dd7ad":{
      "scriptId":"u79"},
    "6a7fe4324a534aac9e1a52799011e3cf":{
      "scriptId":"u80"},
    "887d66d46c0e49f7817302383d080f17":{
      "scriptId":"u81"},
    "b5750ee400134531a58c7d72b0fd6ae9":{
      "scriptId":"u82"},
    "c9cd48e402fb4f45940ef28c85676ab3":{
      "scriptId":"u83"},
    "0206c37d097b4d6d905cd36235a1962d":{
      "scriptId":"u84"},
    "79a39658337146c3a9a2cee5fb276be7":{
      "scriptId":"u85"},
    "6d9d7c00cfd442759e54bce293c07bce":{
      "scriptId":"u86"},
    "76265bb436cf49acbacbc4d0dbe4fd26":{
      "scriptId":"u87"},
    "36c3dda28aa84610b46ec4c1ef7ea9cc":{
      "scriptId":"u88"},
    "c736fb29be55454fa2742f0945276f10":{
      "scriptId":"u89"},
    "4158df36891e4203b571b9e6d798b2f0":{
      "scriptId":"u90"},
    "d5b8067f59824faaa9fbdc99d4a567b0":{
      "scriptId":"u91"},
    "200827577aa942d78c0b361396310b2a":{
      "scriptId":"u92"},
    "1b1961bd4fa34224b72709ca9bad1097":{
      "scriptId":"u93"},
    "d7edaa2cc1b64c3ab17f3754edc16c9e":{
      "scriptId":"u94"},
    "20dc5f3c602545c5b2e1e37fee6ed289":{
      "scriptId":"u95"},
    "3aac8601310a4f718f293f07eab0b2f0":{
      "scriptId":"u96"},
    "85626b7735ba402fb7431cd0a1320f61":{
      "scriptId":"u97"},
    "c09b31d0c09c45ab9e842f58e5eac3fe":{
      "scriptId":"u98"},
    "166b20953d4f490781b2d09f37fd7a84":{
      "scriptId":"u99"},
    "6110328520304372a1ed9e4af1d35805":{
      "scriptId":"u100"},
    "c78ee52a5f8a4825bf68780d1862453a":{
      "scriptId":"u101"},
    "1fd50675e422444f938065a8a24bd437":{
      "scriptId":"u102"},
    "146ffecf1e5d4d509826e4a1ac3d9e44":{
      "scriptId":"u103"},
    "45ef4ca6727c475292730aad16fbf732":{
      "scriptId":"u104"},
    "398125eeb85b4afc9f4fcdced14d3b9d":{
      "scriptId":"u105"},
    "c2490932cdbf44ab836d1afcb00960f2":{
      "scriptId":"u106"},
    "c90453d5d5ad48c7bb24f24e5ba101cb":{
      "scriptId":"u107"},
    "70cf766002b7405fb4d7358f0f4e783e":{
      "scriptId":"u108"},
    "a737b1b13d6b43568522d2f821b0944d":{
      "scriptId":"u109"},
    "dc0b5950bc5e46f3863851b3ae54c3ed":{
      "scriptId":"u110"},
    "a063dcc4911442d39ec60c72a575125d":{
      "scriptId":"u111"},
    "99ec54775d4546b4ae098e51d9e72404":{
      "scriptId":"u112"},
    "a1fc21e9542a4d4a8674063ce8c1aa2b":{
      "scriptId":"u113"},
    "99718426052f41cd9d2a3073508392ef":{
      "scriptId":"u114"}}});