$axure.loadCurrentPage({
  "url":"mt_create1.html",
  "generationDate":new Date(1483926309745.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e80263238ee14c9b8456777cb8e69895",
    "type":"Axure:Page",
    "name":"mt_create1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb0033396a2244ab81ea9a5133eadd42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":69,
              "y":129},
            "size":{
              "width":561,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc621e39045b4e2bb64759b73dbef9c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":69,
                  "y":129},
                "size":{
                  "width":561,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u0.png"}},
{
          "id":"5fdcf1cd31474a3fac1833dcac4014ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":69,
              "y":39},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47fbd092e232451598eca7546528ab1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":69,
                  "y":39},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a76f38ecb640bea69aae42d5261328",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":69,
              "y":84},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"203d525797a44a928f6d6da342a4127a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":69,
                  "y":84},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"c03c4f120fe848c08dabf3db8ed21262",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":98,
              "y":93},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70eab721b79745a4bff5e20855c7f782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":98,
                  "y":93},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15a5a43b6fd545a68ea9429087c39d98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":90,
              "y":86},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed2b60f6d82e4031a71cd929d95b6cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":90,
                  "y":86},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24beaf134f084267aeb3763afc7fd8e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":170,
              "y":86},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"362c85d05be3451681fe7bc40f64da1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":170,
                  "y":86},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4113e8392d0a4b78b0bfc65f64f3ba60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":246,
              "y":86},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44163ce5aea548cdb436a45f68e9b650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":246,
                  "y":86},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f7181866b72410d8a7310f6686c525a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":320,
              "y":86},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7617c15b76b7454a9c224c1738130984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":320,
                  "y":86},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99ac543cc7a84f0caaa74e19db75152c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":394,
              "y":86},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9132c8476074f7f95fa3f8c5b823ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":394,
                  "y":86},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c12a1704e5414207b6af7041482001ad",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":89,
              "y":202},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4e1f48177942dabd9a71419b14561d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48524148870148e49bbf1c83e759b1c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"24f42708cd0147a18c6e241ee79fa6b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55d12baabcde41f39bea76e8aaf9fa44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"9b0a191c44a0467a90b05b64f5efcfc2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":307,
              "y":400},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9706417936864dc2a0c92e02f01aaf33",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":172,
              "y":139},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c8e5623d1284b6d8363531ec691382f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":172,
              "y":172},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c03a0a68ee214d54a8262931d20e85af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":91,
              "y":235},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"0a928ccfe6de4463ba62bb0b642c24b9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":207,
              "y":236},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"0de0a8a2be184089ace775480fe5af40",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":307,
              "y":235},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"56d47908a9e045898a46583dbc023eb2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":487,
              "y":235},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"7bedebfe13bf403e909dcbfa32bcef72",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":386,
              "y":236},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f47787ebb92d4e268fd602a4cb4aa366",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":276,
              "y":143},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374c99e3120b4b9d8a1281adc9a11e9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":276,
                  "y":143},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd9f739d55584f5ba40a29b0eb6b265f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":175},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b582d13872e4df98e97a5dc3dddb203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":175},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a514c2d4ae0431089aebc6552c95134",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":92,
              "y":146},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20c9c6ec89214a2a8ee0f2c90a1bc952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":92,
                  "y":146},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f9e36f1c72e41849cdc2d33209afbc9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":564,
              "y":235},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"48dc93a18eaa47c8ae525130480dd499",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":596,
              "y":235},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3bbc1907011d45cf9c2c8499637e03b1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":91,
              "y":262},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"571880bf8fdd4c99ac3e7780ec1d621f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":207,
              "y":263},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ef43b552c2f04ea0b9f06dc3f3c4d155",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":307,
              "y":262},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"813696535e1c4df8910079b75d1329b7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":487,
              "y":262},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"4c5c204e08964ce0af6eb8221a888ccc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":386,
              "y":263},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dfbbc3ad488b42acbf7b566a1fd1385f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":564,
              "y":262},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"655d24e53a5f466384a77922de236125",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":596,
              "y":262},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mt_create in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mt_create.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "fb0033396a2244ab81ea9a5133eadd42":{
      "scriptId":"u0"},
    "cc621e39045b4e2bb64759b73dbef9c6":{
      "scriptId":"u1"},
    "5fdcf1cd31474a3fac1833dcac4014ea":{
      "scriptId":"u2"},
    "47fbd092e232451598eca7546528ab1e":{
      "scriptId":"u3"},
    "57a76f38ecb640bea69aae42d5261328":{
      "scriptId":"u4"},
    "203d525797a44a928f6d6da342a4127a":{
      "scriptId":"u5"},
    "c03c4f120fe848c08dabf3db8ed21262":{
      "scriptId":"u6"},
    "70eab721b79745a4bff5e20855c7f782":{
      "scriptId":"u7"},
    "15a5a43b6fd545a68ea9429087c39d98":{
      "scriptId":"u8"},
    "ed2b60f6d82e4031a71cd929d95b6cca":{
      "scriptId":"u9"},
    "24beaf134f084267aeb3763afc7fd8e8":{
      "scriptId":"u10"},
    "362c85d05be3451681fe7bc40f64da1b":{
      "scriptId":"u11"},
    "4113e8392d0a4b78b0bfc65f64f3ba60":{
      "scriptId":"u12"},
    "44163ce5aea548cdb436a45f68e9b650":{
      "scriptId":"u13"},
    "2f7181866b72410d8a7310f6686c525a":{
      "scriptId":"u14"},
    "7617c15b76b7454a9c224c1738130984":{
      "scriptId":"u15"},
    "99ac543cc7a84f0caaa74e19db75152c":{
      "scriptId":"u16"},
    "d9132c8476074f7f95fa3f8c5b823ba1":{
      "scriptId":"u17"},
    "c12a1704e5414207b6af7041482001ad":{
      "scriptId":"u18"},
    "6b4e1f48177942dabd9a71419b14561d":{
      "scriptId":"u19"},
    "48524148870148e49bbf1c83e759b1c8":{
      "scriptId":"u20"},
    "24f42708cd0147a18c6e241ee79fa6b9":{
      "scriptId":"u21"},
    "55d12baabcde41f39bea76e8aaf9fa44":{
      "scriptId":"u22"},
    "9b0a191c44a0467a90b05b64f5efcfc2":{
      "scriptId":"u23"},
    "9706417936864dc2a0c92e02f01aaf33":{
      "scriptId":"u24"},
    "0c8e5623d1284b6d8363531ec691382f":{
      "scriptId":"u25"},
    "c03a0a68ee214d54a8262931d20e85af":{
      "scriptId":"u26"},
    "0a928ccfe6de4463ba62bb0b642c24b9":{
      "scriptId":"u27"},
    "0de0a8a2be184089ace775480fe5af40":{
      "scriptId":"u28"},
    "56d47908a9e045898a46583dbc023eb2":{
      "scriptId":"u29"},
    "7bedebfe13bf403e909dcbfa32bcef72":{
      "scriptId":"u30"},
    "f47787ebb92d4e268fd602a4cb4aa366":{
      "scriptId":"u31"},
    "374c99e3120b4b9d8a1281adc9a11e9e":{
      "scriptId":"u32"},
    "cd9f739d55584f5ba40a29b0eb6b265f":{
      "scriptId":"u33"},
    "6b582d13872e4df98e97a5dc3dddb203":{
      "scriptId":"u34"},
    "4a514c2d4ae0431089aebc6552c95134":{
      "scriptId":"u35"},
    "20c9c6ec89214a2a8ee0f2c90a1bc952":{
      "scriptId":"u36"},
    "7f9e36f1c72e41849cdc2d33209afbc9":{
      "scriptId":"u37"},
    "48dc93a18eaa47c8ae525130480dd499":{
      "scriptId":"u38"},
    "3bbc1907011d45cf9c2c8499637e03b1":{
      "scriptId":"u39"},
    "571880bf8fdd4c99ac3e7780ec1d621f":{
      "scriptId":"u40"},
    "ef43b552c2f04ea0b9f06dc3f3c4d155":{
      "scriptId":"u41"},
    "813696535e1c4df8910079b75d1329b7":{
      "scriptId":"u42"},
    "4c5c204e08964ce0af6eb8221a888ccc":{
      "scriptId":"u43"},
    "dfbbc3ad488b42acbf7b566a1fd1385f":{
      "scriptId":"u44"},
    "655d24e53a5f466384a77922de236125":{
      "scriptId":"u45"}}});