$axure.loadCurrentPage({
  "url":"yq_create.html",
  "generationDate":new Date(1483926310988.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f5aeb647377e422ab1844965d43f1182",
    "type":"Axure:Page",
    "name":"yq_create",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"61320714756b4b7f9c810dfcca9a6abe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":511}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb327c5fb044bc88f7b563becf7553c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":511}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/yq_xiugai/u0.png"}},
{
          "id":"a632789bf3554862b79a4c58867ec31c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"629db608d8b34f61b3ac8afd1232edff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"733af691fa054698b004561479bad56a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d917183bcab84d6fa4a66aac1080f309",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"719b8786e6c14d48a2bdf9f6f9b472f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"52a0136f48eb4455a1ae624bf313b37b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7385b45367a452f8e59a4e247e1de46",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"5d2afe2d737744e1b93ca734de462680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b3136361ab4ee0b2aa2854f984c180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"32fbba2fb197401d9e5d82a0da8c54b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38f58703efe45cd8f0306ebf0496283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9049331ccfe8484a9a175283517fa58e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":285,
              "y":588},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5701d452c70e464080d2dfe9ba5f8738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e6068ee7e448519081bf1a7de489da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3068d9c098745759a3e339d64a14c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c9738bf5694e50a6476cc251cfae6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"803e702b25404cfd9c96101d47badd49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7443910a6fe94965901fbc369a2394ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aff86080e02471bb331dfb2564af4b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edaa9cbb3b194023bd2ad77c8c80006b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b25e8dcccf714f3cbdfbc607e23dc3be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b15fbbe142d4698bc71cd00909b0dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab864ed2e2c94d039ded57ac74a77d58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":331},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7610d8008794b629f49ab8382ef9fa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":331},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49e05baf9a56429a98a7d63c73ed036a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":356},
            "size":{
              "width":519,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d828e6ce31fb43308a6d7f57ccfd3806",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"86f051fa34c74b07a1643843e534768b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u27.png"}},
{
              "id":"bfd7aa073c004a4ba00108d9c20291b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0481ddf11c14979be7d69a327f00acb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"5f69ca07ca6b4320acc01e23c76ed918",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d82bb6aff3194708b538574c7df7a209",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"fcb91f573ec64dd192d4f4c0e8295582",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":374,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"643950a5310642bda885d109199cff73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":374,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u33.png"}},
{
              "id":"dd54515360cf41328c8b08ecf20fe273",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fb0c9492fe641b08c3874caf5e5ba82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"8832d692b082400da82b6e7b0ec8824b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3e2c5c7f6264892a976bdc8703e306b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"65fd3e6760884089881f075fbdce5334",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"247504f1481749c692665b2fc89d33f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"055ff2efa24c4b7f8bb6f0b088697cc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0168517ca54a47e2aef7a6768c8947f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"5f76e0276bff44f18d12d8b90b96eae7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21ff96e050ff40279ddf8e6877c7a1a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"782c49a7500049aa8b93c8f6a399bc23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":120},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b821b86c55543bd81c01f31b23b9975",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":120},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"725fb9fb1d54438d90c237de28c68f07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f9d8e29f1d848a2af8f9dd5739f5b50",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"f11bf2b7b58c422abbb5835763301f8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":150},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c30436d4a8c4585b7bd693e8c6f0c60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":150},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"9d142ce99f5e484bb778b870f2774497",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44dd3fcc66ba42b2b4db2fd9c30ba392",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u75.png"}},
{
              "id":"1ec4e82a23cf47c4a1fd48a002135b59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":180},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9994fd40a26d4d3599832fe2250b7b6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":180},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u81.png"}},
{
              "id":"36aaaceda8c44e138c33eb778fb798f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72dbc4fec93745df813fff151efb804a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u29.png"}},
{
              "id":"23f106fd135d48889d19ab88d4125b91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c12e7e3618124479af66ef3b89d6ee2f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"99dd5c39e21847d886d8e36cafeb862d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a2b93a058cd4c98a9ce92b78db06fcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"42ee87c20a4949bc82f4773e7184877b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"874ba4bd5c3d43328c99ac2551a15525",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"bd14652acc694b4f87147b8879e8a292",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":120},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f18003c3e19043c49caa252c43a87fd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":120},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"e5ad72659eb14c80b35b81437c26dd06",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":150},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a064f2959f04474aa4235ccf2b69bff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":150},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"a5e4995e9b77484da3afc82e16ca8281",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":180},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2bca17ea0b942e2abbb594c81225c20",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":180},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u77.png"}},
{
              "id":"39e08c6a2e004071aa8d2e916587a209",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":249,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a83ff91f756a40e9a0e8bd5190d5e019",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":249,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u31.png"}},
{
              "id":"4a737b44250445b8a04ffabb525b8baf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":30},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15ba10a1f60b432f91e2f4fd3c035b0b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"a9f509b175eb41d19e5a6b41d6fe892b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":60},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3943736f8aa8413ba124494c873e521b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":60},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"d0944c24da9544bba7f54d79d97193c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":90},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bb4d059056a4e358ceb62dc37fd2a0e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"2b746f2d4dc24aba90ea4b531a3fdb27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":120},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6e7c7b0d71a4b68b7ade330b3c4dafa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":120},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"19941ee9b13c4a5cbfe3d19a2d22ee98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":150},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a781868c2f584c5f9f9b604bddf9ca4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":150},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"c3435d08523e48e0be020d521b319b7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":180},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"392cfadcecf8428ca0816b5485ae94cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":180},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u79.png"}}]},
{
          "id":"b02545d5b7a24f34a6a5fdd7116284db",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":225},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0b510956fdf54786822b6861de0d6f6d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":225},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f934427241a64c5cb3731eca24885951",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4a0745459b0b409881ccb83d29f3dd10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4426042a17ab48a59e88e7f9f21bdf5e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"ed583d5d59854aacbf0de5810c6c84dc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"291f06f32fd64005b390b83e91c96e66",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"aaba5001e5214002bdc29b0bf7901180",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"70432178be9248578153c24280beac90",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"20703d349ee547d890bf22dc68dae3aa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"6614d57c28d5498783dada2d823ace05",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"6fbdc2bcae354d33952ade6603dd13da",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"1c80a36441d242e48cc079d98c3f8c69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"4ce67780db114938b8bb6409c266ad93",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"94fcc45fc64c4bb88e32043201664e85",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0cb51e35d1ea432f8041095095d6c4e2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9ffb1481944f4b48a2d83d60725bca37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efcd8fbe988e43f6a120cdf7742f952b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ed8d7cdb4f543a5ad188f9c7c1cd480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91bc6f4d2124ac7b7694854d247324f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6382e5de2bd94b1d9206f174b109de4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6e70c67fea4432ead2e351c73983489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"307d2ed5ee9f4a99bcb7e8ff21a9eb62",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yq_create1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yq_create1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"013b633a994c45cb8646e1ac7f1122e4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "61320714756b4b7f9c810dfcca9a6abe":{
      "scriptId":"u0"},
    "cbb327c5fb044bc88f7b563becf7553c":{
      "scriptId":"u1"},
    "a632789bf3554862b79a4c58867ec31c":{
      "scriptId":"u2"},
    "629db608d8b34f61b3ac8afd1232edff":{
      "scriptId":"u3"},
    "733af691fa054698b004561479bad56a":{
      "scriptId":"u4"},
    "d917183bcab84d6fa4a66aac1080f309":{
      "scriptId":"u5"},
    "719b8786e6c14d48a2bdf9f6f9b472f8":{
      "scriptId":"u6"},
    "52a0136f48eb4455a1ae624bf313b37b":{
      "scriptId":"u7"},
    "c7385b45367a452f8e59a4e247e1de46":{
      "scriptId":"u8"},
    "5d2afe2d737744e1b93ca734de462680":{
      "scriptId":"u9"},
    "54b3136361ab4ee0b2aa2854f984c180":{
      "scriptId":"u10"},
    "32fbba2fb197401d9e5d82a0da8c54b0":{
      "scriptId":"u11"},
    "c38f58703efe45cd8f0306ebf0496283":{
      "scriptId":"u12"},
    "9049331ccfe8484a9a175283517fa58e":{
      "scriptId":"u13"},
    "5701d452c70e464080d2dfe9ba5f8738":{
      "scriptId":"u14"},
    "44e6068ee7e448519081bf1a7de489da":{
      "scriptId":"u15"},
    "e3068d9c098745759a3e339d64a14c4b":{
      "scriptId":"u16"},
    "a0c9738bf5694e50a6476cc251cfae6c":{
      "scriptId":"u17"},
    "803e702b25404cfd9c96101d47badd49":{
      "scriptId":"u18"},
    "7443910a6fe94965901fbc369a2394ce":{
      "scriptId":"u19"},
    "9aff86080e02471bb331dfb2564af4b6":{
      "scriptId":"u20"},
    "edaa9cbb3b194023bd2ad77c8c80006b":{
      "scriptId":"u21"},
    "b25e8dcccf714f3cbdfbc607e23dc3be":{
      "scriptId":"u22"},
    "2b15fbbe142d4698bc71cd00909b0dac":{
      "scriptId":"u23"},
    "ab864ed2e2c94d039ded57ac74a77d58":{
      "scriptId":"u24"},
    "b7610d8008794b629f49ab8382ef9fa5":{
      "scriptId":"u25"},
    "49e05baf9a56429a98a7d63c73ed036a":{
      "scriptId":"u26"},
    "d828e6ce31fb43308a6d7f57ccfd3806":{
      "scriptId":"u27"},
    "86f051fa34c74b07a1643843e534768b":{
      "scriptId":"u28"},
    "36aaaceda8c44e138c33eb778fb798f1":{
      "scriptId":"u29"},
    "72dbc4fec93745df813fff151efb804a":{
      "scriptId":"u30"},
    "39e08c6a2e004071aa8d2e916587a209":{
      "scriptId":"u31"},
    "a83ff91f756a40e9a0e8bd5190d5e019":{
      "scriptId":"u32"},
    "fcb91f573ec64dd192d4f4c0e8295582":{
      "scriptId":"u33"},
    "643950a5310642bda885d109199cff73":{
      "scriptId":"u34"},
    "bfd7aa073c004a4ba00108d9c20291b5":{
      "scriptId":"u35"},
    "b0481ddf11c14979be7d69a327f00acb":{
      "scriptId":"u36"},
    "23f106fd135d48889d19ab88d4125b91":{
      "scriptId":"u37"},
    "c12e7e3618124479af66ef3b89d6ee2f":{
      "scriptId":"u38"},
    "4a737b44250445b8a04ffabb525b8baf":{
      "scriptId":"u39"},
    "15ba10a1f60b432f91e2f4fd3c035b0b":{
      "scriptId":"u40"},
    "dd54515360cf41328c8b08ecf20fe273":{
      "scriptId":"u41"},
    "7fb0c9492fe641b08c3874caf5e5ba82":{
      "scriptId":"u42"},
    "5f69ca07ca6b4320acc01e23c76ed918":{
      "scriptId":"u43"},
    "d82bb6aff3194708b538574c7df7a209":{
      "scriptId":"u44"},
    "99dd5c39e21847d886d8e36cafeb862d":{
      "scriptId":"u45"},
    "1a2b93a058cd4c98a9ce92b78db06fcf":{
      "scriptId":"u46"},
    "a9f509b175eb41d19e5a6b41d6fe892b":{
      "scriptId":"u47"},
    "3943736f8aa8413ba124494c873e521b":{
      "scriptId":"u48"},
    "8832d692b082400da82b6e7b0ec8824b":{
      "scriptId":"u49"},
    "a3e2c5c7f6264892a976bdc8703e306b":{
      "scriptId":"u50"},
    "65fd3e6760884089881f075fbdce5334":{
      "scriptId":"u51"},
    "247504f1481749c692665b2fc89d33f4":{
      "scriptId":"u52"},
    "42ee87c20a4949bc82f4773e7184877b":{
      "scriptId":"u53"},
    "874ba4bd5c3d43328c99ac2551a15525":{
      "scriptId":"u54"},
    "d0944c24da9544bba7f54d79d97193c1":{
      "scriptId":"u55"},
    "1bb4d059056a4e358ceb62dc37fd2a0e":{
      "scriptId":"u56"},
    "055ff2efa24c4b7f8bb6f0b088697cc8":{
      "scriptId":"u57"},
    "0168517ca54a47e2aef7a6768c8947f6":{
      "scriptId":"u58"},
    "5f76e0276bff44f18d12d8b90b96eae7":{
      "scriptId":"u59"},
    "21ff96e050ff40279ddf8e6877c7a1a7":{
      "scriptId":"u60"},
    "bd14652acc694b4f87147b8879e8a292":{
      "scriptId":"u61"},
    "f18003c3e19043c49caa252c43a87fd6":{
      "scriptId":"u62"},
    "2b746f2d4dc24aba90ea4b531a3fdb27":{
      "scriptId":"u63"},
    "e6e7c7b0d71a4b68b7ade330b3c4dafa":{
      "scriptId":"u64"},
    "782c49a7500049aa8b93c8f6a399bc23":{
      "scriptId":"u65"},
    "4b821b86c55543bd81c01f31b23b9975":{
      "scriptId":"u66"},
    "725fb9fb1d54438d90c237de28c68f07":{
      "scriptId":"u67"},
    "0f9d8e29f1d848a2af8f9dd5739f5b50":{
      "scriptId":"u68"},
    "e5ad72659eb14c80b35b81437c26dd06":{
      "scriptId":"u69"},
    "8a064f2959f04474aa4235ccf2b69bff":{
      "scriptId":"u70"},
    "19941ee9b13c4a5cbfe3d19a2d22ee98":{
      "scriptId":"u71"},
    "a781868c2f584c5f9f9b604bddf9ca4a":{
      "scriptId":"u72"},
    "f11bf2b7b58c422abbb5835763301f8e":{
      "scriptId":"u73"},
    "0c30436d4a8c4585b7bd693e8c6f0c60":{
      "scriptId":"u74"},
    "9d142ce99f5e484bb778b870f2774497":{
      "scriptId":"u75"},
    "44dd3fcc66ba42b2b4db2fd9c30ba392":{
      "scriptId":"u76"},
    "a5e4995e9b77484da3afc82e16ca8281":{
      "scriptId":"u77"},
    "e2bca17ea0b942e2abbb594c81225c20":{
      "scriptId":"u78"},
    "c3435d08523e48e0be020d521b319b7e":{
      "scriptId":"u79"},
    "392cfadcecf8428ca0816b5485ae94cc":{
      "scriptId":"u80"},
    "1ec4e82a23cf47c4a1fd48a002135b59":{
      "scriptId":"u81"},
    "9994fd40a26d4d3599832fe2250b7b6f":{
      "scriptId":"u82"},
    "b02545d5b7a24f34a6a5fdd7116284db":{
      "scriptId":"u83"},
    "0b510956fdf54786822b6861de0d6f6d":{
      "scriptId":"u84"},
    "f934427241a64c5cb3731eca24885951":{
      "scriptId":"u85"},
    "4a0745459b0b409881ccb83d29f3dd10":{
      "scriptId":"u86"},
    "4426042a17ab48a59e88e7f9f21bdf5e":{
      "scriptId":"u87"},
    "ed583d5d59854aacbf0de5810c6c84dc":{
      "scriptId":"u88"},
    "291f06f32fd64005b390b83e91c96e66":{
      "scriptId":"u89"},
    "aaba5001e5214002bdc29b0bf7901180":{
      "scriptId":"u90"},
    "70432178be9248578153c24280beac90":{
      "scriptId":"u91"},
    "20703d349ee547d890bf22dc68dae3aa":{
      "scriptId":"u92"},
    "6614d57c28d5498783dada2d823ace05":{
      "scriptId":"u93"},
    "6fbdc2bcae354d33952ade6603dd13da":{
      "scriptId":"u94"},
    "1c80a36441d242e48cc079d98c3f8c69":{
      "scriptId":"u95"},
    "4ce67780db114938b8bb6409c266ad93":{
      "scriptId":"u96"},
    "94fcc45fc64c4bb88e32043201664e85":{
      "scriptId":"u97"},
    "0cb51e35d1ea432f8041095095d6c4e2":{
      "scriptId":"u98"},
    "9ffb1481944f4b48a2d83d60725bca37":{
      "scriptId":"u99"},
    "efcd8fbe988e43f6a120cdf7742f952b":{
      "scriptId":"u100"},
    "7ed8d7cdb4f543a5ad188f9c7c1cd480":{
      "scriptId":"u101"},
    "a91bc6f4d2124ac7b7694854d247324f":{
      "scriptId":"u102"},
    "6382e5de2bd94b1d9206f174b109de4a":{
      "scriptId":"u103"},
    "a6e70c67fea4432ead2e351c73983489":{
      "scriptId":"u104"},
    "307d2ed5ee9f4a99bcb7e8ff21a9eb62":{
      "scriptId":"u105"},
    "013b633a994c45cb8646e1ac7f1122e4":{
      "scriptId":"u106"}}});