$axure.loadCurrentPage({
  "url":"jia_1.html",
  "generationDate":new Date(1483926309545.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dfd8a0a1a3dd46d4926362276512079c",
    "type":"Axure:Page",
    "name":"jia",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42730690f4c643ff82a2b97bc3071075",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":311}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e75b46b6f34ac7ba07ea07d85d8a7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":311}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u0.png"}},
{
          "id":"09044af363cc45ee880da694b1b5dead",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4d3b9349c34a59ac4b02fe61519076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72ec19b553744611bc4f0aba2116794e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"154c1738452245d9a85794e28a1ffd02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"91950d53a0d94f2186885883ed1fc927",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a5df2cd0854714828db2e842756113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34ddcb990d424944b88bf82e2bc57e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5514260eb1aa4aeaacc90442671e6ca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9d2865a3b734447b83ee31ec6a8eaeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddf9aee5b85945e8bb23bcde6b8affca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8e1cb6ad7234ed59b4a19c2bf64a620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff59da25f164893b71568baffe0d8cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"998b8b59c44a4bc7a06eea77876cf4f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa7cf223b8a2409fb7c835adcca9ca23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a03089bf0e784effb60253f8c9779ab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e18543f49c4ba68a0e210dadc7f98a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91fa3c863baf4945a4bd55d83b163548",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":192},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6734025187d54823b187867b782cd5d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62731c9084d34154a47d12fb59e79875",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"57308b2341494ea99f70c6abbc110822",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d6d85737c6049c39c3fa425de073668",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"a4431ab324d848c38b09b581dcbacb3e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":390},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"040bf58bf9cd49a89fb8ca7bb9b6fa33",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9940e90aae0d49c4bfd29815e80345ad",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ad73caa4693744b1ae1a899a02255957",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":225},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"038cd796970c408398654a48d1b8641d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5e975a531a5b410c96a6c550564baa77",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"deec463396c24753bc936c5415900fc4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":225},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"72456b44447447eda0c86caa386e2357",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":226},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7f161a8e3ded46feb68e69cb746aa791",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":252},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"780155afba094d788ff657cfa0fbbe1a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"971fe28c89dd4867902a6de8e539d3e1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"aa2d26c13eeb4062b5d9418ebe3b6635",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":252},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"24a4787e2e8c4532bebe910f028f6984",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":253},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bf17c688cd244e68b360dcccb7ef97e4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":280},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"d6e0b974cc5b4830bd63e3a9ade4329f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7279cabecb864ccda4279b13cfc03d62",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"be1df44b69e8481fa8e4ecb6ec035a95",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":280},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"5dde0fbbb38545199e2a0c0d91c4cfd9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":281},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3853668252d447fc9a8ba6f538e2f2e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5294a1070114b6fa5e6eeb0e4daf17b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8a0d7d0b01b43aa998b7f699ffa7e3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b222e0e748da4ca594af132599f13b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8034c571575e4a4c99ddba5820668747",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11aba916da0646fcb57f9ee5638a6dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9af2f39def24f60b042ac5b4041c3a8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e59dbe8301db49719bc2f8b06526b78a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":225},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b88d7d67f3c2417bba2357447b486549",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8a216c1a0f1b499ebd0a4139b2c8d3b7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":252},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7c3746744bdf4c378ebaf62f6418e605",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5b07fcdaa44f48cba5dadfde3d3e2bad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":279},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6098556ba970470a8494b014a24ddaf7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":306},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"095e9439f9074231a3d3172946498a61",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":307},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"11b54d94b2c84b81aae92a4ae57fd892",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":306},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"bf4da9bc6d1f4d9eb6d5d87df19a902d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":306},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"57183f63f6af40018f416543820f9e85",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":307},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c351c1ec5c3e4c988d6ea0b02c01a337",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":334},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"c1b5d0b73391491ba6e766f854f7edff",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":335},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5e9157a7196c4bf8a544be9be027d3d3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":334},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"2e230b8769804c3288cf57b471c42c52",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":334},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"0d8f5e8d1a24402587a1519f9f1c18ab",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":335},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"295929d4d5394f738ed66924533fe5c1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":306},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a8bd0b61b926461f947e57abf3f1f7ce",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":306},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"44ece877f6fb43f8824056f1f66002f1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":333},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e79a3008ddda44459ee3f77b5b414d24",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":333},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8d5d6d52541d4bd8aa5dcad194cbb703",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":81,
              "y":360},
            "size":{
              "width":114,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"c25f5de5bc7b4818a006a05168c21cb0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":197,
              "y":361},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3214b25fdb594ecfa7a2c6de720e6b67",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":297,
              "y":360},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"0ae98e0345dd4b4d966c5907f9a2c2a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":477,
              "y":360},
            "size":{
              "width":76,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"4fcd7761945f4d138c1f1ac8ac56f837",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":376,
              "y":361},
            "size":{
              "width":97,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"39e56e940ee5476a8594a352e65bc3e3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":554,
              "y":359},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f50707c94b6148fd99d87d1fde6278e6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":586,
              "y":359},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mt_xiugai in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mt_xiugai.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "42730690f4c643ff82a2b97bc3071075":{
      "scriptId":"u0"},
    "b2e75b46b6f34ac7ba07ea07d85d8a7b":{
      "scriptId":"u1"},
    "09044af363cc45ee880da694b1b5dead":{
      "scriptId":"u2"},
    "ec4d3b9349c34a59ac4b02fe61519076":{
      "scriptId":"u3"},
    "72ec19b553744611bc4f0aba2116794e":{
      "scriptId":"u4"},
    "154c1738452245d9a85794e28a1ffd02":{
      "scriptId":"u5"},
    "91950d53a0d94f2186885883ed1fc927":{
      "scriptId":"u6"},
    "86a5df2cd0854714828db2e842756113":{
      "scriptId":"u7"},
    "34ddcb990d424944b88bf82e2bc57e84":{
      "scriptId":"u8"},
    "5514260eb1aa4aeaacc90442671e6ca8":{
      "scriptId":"u9"},
    "d9d2865a3b734447b83ee31ec6a8eaeb":{
      "scriptId":"u10"},
    "ddf9aee5b85945e8bb23bcde6b8affca":{
      "scriptId":"u11"},
    "b8e1cb6ad7234ed59b4a19c2bf64a620":{
      "scriptId":"u12"},
    "9ff59da25f164893b71568baffe0d8cd":{
      "scriptId":"u13"},
    "998b8b59c44a4bc7a06eea77876cf4f8":{
      "scriptId":"u14"},
    "aa7cf223b8a2409fb7c835adcca9ca23":{
      "scriptId":"u15"},
    "a03089bf0e784effb60253f8c9779ab8":{
      "scriptId":"u16"},
    "39e18543f49c4ba68a0e210dadc7f98a":{
      "scriptId":"u17"},
    "91fa3c863baf4945a4bd55d83b163548":{
      "scriptId":"u18"},
    "6734025187d54823b187867b782cd5d8":{
      "scriptId":"u19"},
    "62731c9084d34154a47d12fb59e79875":{
      "scriptId":"u20"},
    "57308b2341494ea99f70c6abbc110822":{
      "scriptId":"u21"},
    "9d6d85737c6049c39c3fa425de073668":{
      "scriptId":"u22"},
    "a4431ab324d848c38b09b581dcbacb3e":{
      "scriptId":"u23"},
    "040bf58bf9cd49a89fb8ca7bb9b6fa33":{
      "scriptId":"u24"},
    "9940e90aae0d49c4bfd29815e80345ad":{
      "scriptId":"u25"},
    "ad73caa4693744b1ae1a899a02255957":{
      "scriptId":"u26"},
    "038cd796970c408398654a48d1b8641d":{
      "scriptId":"u27"},
    "5e975a531a5b410c96a6c550564baa77":{
      "scriptId":"u28"},
    "deec463396c24753bc936c5415900fc4":{
      "scriptId":"u29"},
    "72456b44447447eda0c86caa386e2357":{
      "scriptId":"u30"},
    "7f161a8e3ded46feb68e69cb746aa791":{
      "scriptId":"u31"},
    "780155afba094d788ff657cfa0fbbe1a":{
      "scriptId":"u32"},
    "971fe28c89dd4867902a6de8e539d3e1":{
      "scriptId":"u33"},
    "aa2d26c13eeb4062b5d9418ebe3b6635":{
      "scriptId":"u34"},
    "24a4787e2e8c4532bebe910f028f6984":{
      "scriptId":"u35"},
    "bf17c688cd244e68b360dcccb7ef97e4":{
      "scriptId":"u36"},
    "d6e0b974cc5b4830bd63e3a9ade4329f":{
      "scriptId":"u37"},
    "7279cabecb864ccda4279b13cfc03d62":{
      "scriptId":"u38"},
    "be1df44b69e8481fa8e4ecb6ec035a95":{
      "scriptId":"u39"},
    "5dde0fbbb38545199e2a0c0d91c4cfd9":{
      "scriptId":"u40"},
    "3853668252d447fc9a8ba6f538e2f2e7":{
      "scriptId":"u41"},
    "b5294a1070114b6fa5e6eeb0e4daf17b":{
      "scriptId":"u42"},
    "b8a0d7d0b01b43aa998b7f699ffa7e3f":{
      "scriptId":"u43"},
    "b222e0e748da4ca594af132599f13b78":{
      "scriptId":"u44"},
    "8034c571575e4a4c99ddba5820668747":{
      "scriptId":"u45"},
    "11aba916da0646fcb57f9ee5638a6dae":{
      "scriptId":"u46"},
    "f9af2f39def24f60b042ac5b4041c3a8":{
      "scriptId":"u47"},
    "e59dbe8301db49719bc2f8b06526b78a":{
      "scriptId":"u48"},
    "b88d7d67f3c2417bba2357447b486549":{
      "scriptId":"u49"},
    "8a216c1a0f1b499ebd0a4139b2c8d3b7":{
      "scriptId":"u50"},
    "7c3746744bdf4c378ebaf62f6418e605":{
      "scriptId":"u51"},
    "5b07fcdaa44f48cba5dadfde3d3e2bad":{
      "scriptId":"u52"},
    "6098556ba970470a8494b014a24ddaf7":{
      "scriptId":"u53"},
    "095e9439f9074231a3d3172946498a61":{
      "scriptId":"u54"},
    "11b54d94b2c84b81aae92a4ae57fd892":{
      "scriptId":"u55"},
    "bf4da9bc6d1f4d9eb6d5d87df19a902d":{
      "scriptId":"u56"},
    "57183f63f6af40018f416543820f9e85":{
      "scriptId":"u57"},
    "c351c1ec5c3e4c988d6ea0b02c01a337":{
      "scriptId":"u58"},
    "c1b5d0b73391491ba6e766f854f7edff":{
      "scriptId":"u59"},
    "5e9157a7196c4bf8a544be9be027d3d3":{
      "scriptId":"u60"},
    "2e230b8769804c3288cf57b471c42c52":{
      "scriptId":"u61"},
    "0d8f5e8d1a24402587a1519f9f1c18ab":{
      "scriptId":"u62"},
    "295929d4d5394f738ed66924533fe5c1":{
      "scriptId":"u63"},
    "a8bd0b61b926461f947e57abf3f1f7ce":{
      "scriptId":"u64"},
    "44ece877f6fb43f8824056f1f66002f1":{
      "scriptId":"u65"},
    "e79a3008ddda44459ee3f77b5b414d24":{
      "scriptId":"u66"},
    "8d5d6d52541d4bd8aa5dcad194cbb703":{
      "scriptId":"u67"},
    "c25f5de5bc7b4818a006a05168c21cb0":{
      "scriptId":"u68"},
    "3214b25fdb594ecfa7a2c6de720e6b67":{
      "scriptId":"u69"},
    "0ae98e0345dd4b4d966c5907f9a2c2a1":{
      "scriptId":"u70"},
    "4fcd7761945f4d138c1f1ac8ac56f837":{
      "scriptId":"u71"},
    "39e56e940ee5476a8594a352e65bc3e3":{
      "scriptId":"u72"},
    "f50707c94b6148fd99d87d1fde6278e6":{
      "scriptId":"u73"}}});