$axure.loadCurrentPage({
  "url":"yq_xiugai.html",
  "generationDate":new Date(1483926310519.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d90c65d8b26b4dff8d5556dc2bd7fbed",
    "type":"Axure:Page",
    "name":"yq_xiugai",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7a5464dd492b44d5ba1363f3ce1f75b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":59,
              "y":119},
            "size":{
              "width":561,
              "height":511}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5cff912db6240898ff88d24efc8b109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":59,
                  "y":119},
                "size":{
                  "width":561,
                  "height":511}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/yq_xiugai/u0.png"}},
{
          "id":"d12776d158e4442badb68eb76ded0e36",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"28px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003399,
              "opacity":1},
            "location":{
              "x":59,
              "y":29},
            "size":{
              "width":337,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a2f16e113af461a9bef41317bc1c5de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"28px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003399,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":29},
                "size":{
                  "width":337,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c7a220e1a684eeb902a966777f3702e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":475,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0ae3603a89e44bc9900609b572e017b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "size":{
                  "width":115,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b839de8dd16d4c0191b9b1116a2089ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "size":{
                      "width":115,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u5.png"}},
{
              "id":"8afe14c5b7a3409aaa56a469e067d8e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF33},
                "location":{
                  "x":115,
                  "y":0},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f6815b20f3a4b98b3cbf5d231eade95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF33},
                    "location":{
                      "x":115,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/hg_xiugai/u7.png"}}]},
{
          "id":"c08a5df39cc54c7bb2f2dee283d6ae59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF417ED6},
{
                  "color":0xFF417ED6},
{
                  "color":0xFF3166C7},
{
                  "color":0xFF3166C7}]},
            "location":{
              "x":59,
              "y":74},
            "size":{
              "width":561,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c23a5994f24f109d240e52ba6bd71f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF417ED6},
{
                      "color":0xFF417ED6},
{
                      "color":0xFF3166C7},
{
                      "color":0xFF3166C7}]},
                "location":{
                  "x":59,
                  "y":74},
                "size":{
                  "width":561,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/hgjj/u24.png"}},
{
          "id":"82ea6f88bf6044cdafd7587b444be74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "fontSize":"14px",
            "location":{
              "x":88,
              "y":83},
            "size":{
              "width":464,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0e0614f09a5481291f0b3747936e5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "fontSize":"14px",
                "location":{
                  "x":88,
                  "y":83},
                "size":{
                  "width":464,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a2c3823190e49cdb5f6745d863539f7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":285,
              "y":588},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"07cea92579fe42c7896e35ff618a7adc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":76},
            "size":{
              "width":70,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898edff5119d49a4a1511a1d7ce795f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":80,
                  "y":76},
                "size":{
                  "width":70,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open hgjj in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"hgjj.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"109676638f0d43708662966617bcb551",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":160,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ffbeaff49c342f1a173f48e943813f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open mthy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"mthy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"770ca66c76d241ada0506eed8bc310f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":236,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"266ef78cdd36413ab45a177a1eee3a44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":236,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open dlhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dlhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18905a586770430ebcc6000ffa9ca90d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":310,
              "y":76},
            "size":{
              "width":60,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eefe60fabe014a2db0404e3f963e1095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":310,
                  "y":76},
                "size":{
                  "width":60,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open yqhy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"yqhy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"145db5e878de4bd6b2ba65d616d431ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":384,
              "y":76},
            "size":{
              "width":96,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e79b10e9c6c4ecaac350ce814c16f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "location":{
                  "x":384,
                  "y":76},
                "size":{
                  "width":96,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jtys in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jtys.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de79a46b50b046c79be5a76bd5f88d80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":331},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6f951c740e4807b7549c2c105d25d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":331},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e397fb03a7a441496b6263421cde6d4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":80,
              "y":356},
            "size":{
              "width":519,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88c4cc65505439bb04e661640ccace9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23ebdfd974434a8e92eecf5930245ec0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u27.png"}},
{
              "id":"9f193701133f455092335d546fce1de3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"10600f7250ab4a8294ba7db12155235f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"843c15e34a7c486f97bd23b2d22740ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"628d121af454457cbc0ad6ab09571bb4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"26988503fe4d48bd8b8bad95498860aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":374,
                  "y":0},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d6e7175fd484bca85394a628d493ef8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":374,
                      "y":0},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u33.png"}},
{
              "id":"d46f8bda9c9242369b28a3765c1e3b62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":30},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"239b5e37621a442cb83e17333a4033d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":30},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"4c8f0528cf664410bfc54dc9bb44066f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":60},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e9f02f8f28c44a99b6bcebc54df898b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":60},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"8fcca65e74ec46929b6d15bf00d4f8fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ffcc9eef92974d6db55d8664f3fa3f79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"cdafafe857c042f381f0e0ba26ce7188",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":90},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2941978c4cf4f2ebebbc5959a9022ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":90},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"ea486a97a9ae41f59ec283bc6ace147d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a194867150c948b0b94389c2f5a95266",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"5c2957cb722d456bab7fee3c190e3670",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":120},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"151b3577d1c4480bad15293a7216386e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":120},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"0363a816097a477d83b6b93393e45393",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"313eef87e83f4c72be80a653dedc75f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u35.png"}},
{
              "id":"6ac17f976b3a4b7991c5dad12aa424ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":150},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"879c8cea548943a58e7d8422fe520d03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":150},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u41.png"}},
{
              "id":"dfe310940f034dfca30ccacc7b067530",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":113,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb1b2e7b50ff4ae5ba306fed71a064d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":113,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u75.png"}},
{
              "id":"b49e0b810ff44fb4b21c3002267f8dfa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":374,
                  "y":180},
                "size":{
                  "width":138,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c44b0e0d6a9c4b35b4159cc04a14be6a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":374,
                      "y":180},
                    "size":{
                      "width":138,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u81.png"}},
{
              "id":"1f588dcb1d884c2cbc6371a419259b78",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":113,
                  "y":0},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cea27d1888c647259729afea46e93fb4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":113,
                      "y":0},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u29.png"}},
{
              "id":"f52533da4bc94d5789bc1487e0ca3fa0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":30},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"096586827c6643edaf7500264348e290",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":30},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"e7588f62e6424a77b669efde375acef6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":60},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db35d911f1ea4b15aa64bf680f9637f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":60},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"bc2ea507be1d4516b8219e71d3fa2a98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":90},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50dcb94c57984f5385aa029470c6ebc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":90},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"9be0de91b109405581aa0246025cfae4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":120},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9236eca0df4424d8a53ebbaab73f3a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":120},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"2a1e217f5772461aaed5831d108db718",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":150},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f48d23897aa94ad7a9da7bf68b480369",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":150},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u37.png"}},
{
              "id":"317104f658844980abfd746401a00c7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":113,
                  "y":180},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"829836cf6cff4756bfb0aa76d5728f60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":113,
                      "y":180},
                    "size":{
                      "width":136,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u77.png"}},
{
              "id":"fc17bdc8a6f04aebbc3dcb3d7ebfc467",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":249,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d4821755fe048b0bd58fcb21b28fe97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCFFFF},
                    "location":{
                      "x":249,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u31.png"}},
{
              "id":"430cf9f0859a4bbbadcdfe6be1150e76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":30},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0793ef97bcb74019bf44c53ad81a9cbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"043dc86b0f6a4431be3a93a26d9f3a4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":60},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5d8dc034d3042f6945f3af9ef22d2ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":60},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"8f3f482aeb9a44ef8aa2146dd2743c6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":90},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2a106893a8743c4acd40227cbe22b60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"74c7c474bce64b3eb239e20d21cb6ce6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":120},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dec2e54e3bf24be9a1cb847fc0846f6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":120},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"c3455363cc72435b9d5eaa8d48e6246a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":150},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f86584dea3844899027bc7788ed9614",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":150},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u39.png"}},
{
              "id":"c5e61a7c547b45ea8f7c8c0943effd73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Regular', '应用字体'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":249,
                  "y":180},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"728edbb0776f4d2f9b100e8cc275799e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'应用字体 Regular', '应用字体'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":249,
                      "y":180},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yq_xiugai/u79.png"}}]},
{
          "id":"ed0fabf4d8a64004905209946e06aca3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":225},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"76670d728568426282b96eff21881c67",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":255},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9350d9a101bf4333a8527bb54c96d94d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":255},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b46fa94cb24e44a79399df1faa97a7ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":225},
            "size":{
              "width":358,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c444fbcc9b24d87bd97a141d9e36794",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"b24393347b9f40f88968d82609ceb8c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"7d3ae5df33a44674845c087af1881a22",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"c9a7adf1e86e4f0e92564c06c4d34e6c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"6a2260d3604a4437a6d930aaaaab8146",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"a6b79955a595452baf5d9fc221640a64",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":196,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"473b2c74df924c7d81105aae3ca6b0e1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":387},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"3cd85e97bef54684951b715044dadc38",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":416},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"75aead4644e647a9a8bb3c24169fc702",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":447},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"14d5326a9eb64820b75f6d6098de0b7a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":476},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"dd43b5b2556f42d28312faeccac640c3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":507},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"1c1122920e9a434b9b10ac15c58bf843",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "horizontalAlignment":"center",
            "location":{
              "x":456,
              "y":536},
            "size":{
              "width":134,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"689031384b34422e9eb241a8a27c1900",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":129},
            "size":{
              "width":68,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e489e23101c44c5be7666570951f648",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":162,
              "y":162},
            "size":{
              "width":68,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2eac595630ab48ce8617b891384f1d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":266,
              "y":133},
            "size":{
              "width":280,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507fb6a1f68c4dc885c9b7b85b6df428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":266,
                  "y":133},
                "size":{
                  "width":280,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c8560dea7114e72984ad19ef8237cf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":165},
            "size":{
              "width":66,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f23abbceafa48589c8d82df26556230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":165},
                "size":{
                  "width":66,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"571b04e95ae94ba9bb72464c42a8fe7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Bold', '应用字体'",
            "fontWeight":"700",
            "location":{
              "x":82,
              "y":136},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0e951241744ebd9836e33ebcb3fbff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'应用字体 Bold', '应用字体'",
                "fontWeight":"700",
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87d3748b8937444dbebfd4efe493b822",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e14bc74319d49b986ef8e267f4de982",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":226},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"221cdc5ccbf5435f8ae44cd8cce1d65f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":555,
              "y":253},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jia in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jia_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6f95ce2eb24f409c973e6cac6bf94db7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'应用字体 Regular', '应用字体'",
            "location":{
              "x":587,
              "y":253},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open jian in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"jian_3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7a5464dd492b44d5ba1363f3ce1f75b6":{
      "scriptId":"u0"},
    "f5cff912db6240898ff88d24efc8b109":{
      "scriptId":"u1"},
    "d12776d158e4442badb68eb76ded0e36":{
      "scriptId":"u2"},
    "2a2f16e113af461a9bef41317bc1c5de":{
      "scriptId":"u3"},
    "4c7a220e1a684eeb902a966777f3702e":{
      "scriptId":"u4"},
    "c0ae3603a89e44bc9900609b572e017b":{
      "scriptId":"u5"},
    "b839de8dd16d4c0191b9b1116a2089ac":{
      "scriptId":"u6"},
    "8afe14c5b7a3409aaa56a469e067d8e5":{
      "scriptId":"u7"},
    "6f6815b20f3a4b98b3cbf5d231eade95":{
      "scriptId":"u8"},
    "c08a5df39cc54c7bb2f2dee283d6ae59":{
      "scriptId":"u9"},
    "29c23a5994f24f109d240e52ba6bd71f":{
      "scriptId":"u10"},
    "82ea6f88bf6044cdafd7587b444be74d":{
      "scriptId":"u11"},
    "d0e0614f09a5481291f0b3747936e5fd":{
      "scriptId":"u12"},
    "8a2c3823190e49cdb5f6745d863539f7":{
      "scriptId":"u13"},
    "07cea92579fe42c7896e35ff618a7adc":{
      "scriptId":"u14"},
    "898edff5119d49a4a1511a1d7ce795f8":{
      "scriptId":"u15"},
    "109676638f0d43708662966617bcb551":{
      "scriptId":"u16"},
    "4ffbeaff49c342f1a173f48e943813f8":{
      "scriptId":"u17"},
    "770ca66c76d241ada0506eed8bc310f6":{
      "scriptId":"u18"},
    "266ef78cdd36413ab45a177a1eee3a44":{
      "scriptId":"u19"},
    "18905a586770430ebcc6000ffa9ca90d":{
      "scriptId":"u20"},
    "eefe60fabe014a2db0404e3f963e1095":{
      "scriptId":"u21"},
    "145db5e878de4bd6b2ba65d616d431ea":{
      "scriptId":"u22"},
    "9e79b10e9c6c4ecaac350ce814c16f6a":{
      "scriptId":"u23"},
    "de79a46b50b046c79be5a76bd5f88d80":{
      "scriptId":"u24"},
    "fe6f951c740e4807b7549c2c105d25d1":{
      "scriptId":"u25"},
    "6e397fb03a7a441496b6263421cde6d4":{
      "scriptId":"u26"},
    "b88c4cc65505439bb04e661640ccace9":{
      "scriptId":"u27"},
    "23ebdfd974434a8e92eecf5930245ec0":{
      "scriptId":"u28"},
    "1f588dcb1d884c2cbc6371a419259b78":{
      "scriptId":"u29"},
    "cea27d1888c647259729afea46e93fb4":{
      "scriptId":"u30"},
    "fc17bdc8a6f04aebbc3dcb3d7ebfc467":{
      "scriptId":"u31"},
    "4d4821755fe048b0bd58fcb21b28fe97":{
      "scriptId":"u32"},
    "26988503fe4d48bd8b8bad95498860aa":{
      "scriptId":"u33"},
    "9d6e7175fd484bca85394a628d493ef8":{
      "scriptId":"u34"},
    "9f193701133f455092335d546fce1de3":{
      "scriptId":"u35"},
    "10600f7250ab4a8294ba7db12155235f":{
      "scriptId":"u36"},
    "f52533da4bc94d5789bc1487e0ca3fa0":{
      "scriptId":"u37"},
    "096586827c6643edaf7500264348e290":{
      "scriptId":"u38"},
    "430cf9f0859a4bbbadcdfe6be1150e76":{
      "scriptId":"u39"},
    "0793ef97bcb74019bf44c53ad81a9cbc":{
      "scriptId":"u40"},
    "d46f8bda9c9242369b28a3765c1e3b62":{
      "scriptId":"u41"},
    "239b5e37621a442cb83e17333a4033d2":{
      "scriptId":"u42"},
    "843c15e34a7c486f97bd23b2d22740ac":{
      "scriptId":"u43"},
    "628d121af454457cbc0ad6ab09571bb4":{
      "scriptId":"u44"},
    "e7588f62e6424a77b669efde375acef6":{
      "scriptId":"u45"},
    "db35d911f1ea4b15aa64bf680f9637f4":{
      "scriptId":"u46"},
    "043dc86b0f6a4431be3a93a26d9f3a4c":{
      "scriptId":"u47"},
    "a5d8dc034d3042f6945f3af9ef22d2ad":{
      "scriptId":"u48"},
    "4c8f0528cf664410bfc54dc9bb44066f":{
      "scriptId":"u49"},
    "5e9f02f8f28c44a99b6bcebc54df898b":{
      "scriptId":"u50"},
    "8fcca65e74ec46929b6d15bf00d4f8fe":{
      "scriptId":"u51"},
    "ffcc9eef92974d6db55d8664f3fa3f79":{
      "scriptId":"u52"},
    "bc2ea507be1d4516b8219e71d3fa2a98":{
      "scriptId":"u53"},
    "50dcb94c57984f5385aa029470c6ebc9":{
      "scriptId":"u54"},
    "8f3f482aeb9a44ef8aa2146dd2743c6d":{
      "scriptId":"u55"},
    "a2a106893a8743c4acd40227cbe22b60":{
      "scriptId":"u56"},
    "cdafafe857c042f381f0e0ba26ce7188":{
      "scriptId":"u57"},
    "a2941978c4cf4f2ebebbc5959a9022ff":{
      "scriptId":"u58"},
    "ea486a97a9ae41f59ec283bc6ace147d":{
      "scriptId":"u59"},
    "a194867150c948b0b94389c2f5a95266":{
      "scriptId":"u60"},
    "9be0de91b109405581aa0246025cfae4":{
      "scriptId":"u61"},
    "e9236eca0df4424d8a53ebbaab73f3a4":{
      "scriptId":"u62"},
    "74c7c474bce64b3eb239e20d21cb6ce6":{
      "scriptId":"u63"},
    "dec2e54e3bf24be9a1cb847fc0846f6f":{
      "scriptId":"u64"},
    "5c2957cb722d456bab7fee3c190e3670":{
      "scriptId":"u65"},
    "151b3577d1c4480bad15293a7216386e":{
      "scriptId":"u66"},
    "0363a816097a477d83b6b93393e45393":{
      "scriptId":"u67"},
    "313eef87e83f4c72be80a653dedc75f6":{
      "scriptId":"u68"},
    "2a1e217f5772461aaed5831d108db718":{
      "scriptId":"u69"},
    "f48d23897aa94ad7a9da7bf68b480369":{
      "scriptId":"u70"},
    "c3455363cc72435b9d5eaa8d48e6246a":{
      "scriptId":"u71"},
    "6f86584dea3844899027bc7788ed9614":{
      "scriptId":"u72"},
    "6ac17f976b3a4b7991c5dad12aa424ca":{
      "scriptId":"u73"},
    "879c8cea548943a58e7d8422fe520d03":{
      "scriptId":"u74"},
    "dfe310940f034dfca30ccacc7b067530":{
      "scriptId":"u75"},
    "fb1b2e7b50ff4ae5ba306fed71a064d3":{
      "scriptId":"u76"},
    "317104f658844980abfd746401a00c7d":{
      "scriptId":"u77"},
    "829836cf6cff4756bfb0aa76d5728f60":{
      "scriptId":"u78"},
    "c5e61a7c547b45ea8f7c8c0943effd73":{
      "scriptId":"u79"},
    "728edbb0776f4d2f9b100e8cc275799e":{
      "scriptId":"u80"},
    "b49e0b810ff44fb4b21c3002267f8dfa":{
      "scriptId":"u81"},
    "c44b0e0d6a9c4b35b4159cc04a14be6a":{
      "scriptId":"u82"},
    "ed0fabf4d8a64004905209946e06aca3":{
      "scriptId":"u83"},
    "76670d728568426282b96eff21881c67":{
      "scriptId":"u84"},
    "9350d9a101bf4333a8527bb54c96d94d":{
      "scriptId":"u85"},
    "b46fa94cb24e44a79399df1faa97a7ae":{
      "scriptId":"u86"},
    "0c444fbcc9b24d87bd97a141d9e36794":{
      "scriptId":"u87"},
    "b24393347b9f40f88968d82609ceb8c3":{
      "scriptId":"u88"},
    "7d3ae5df33a44674845c087af1881a22":{
      "scriptId":"u89"},
    "c9a7adf1e86e4f0e92564c06c4d34e6c":{
      "scriptId":"u90"},
    "6a2260d3604a4437a6d930aaaaab8146":{
      "scriptId":"u91"},
    "a6b79955a595452baf5d9fc221640a64":{
      "scriptId":"u92"},
    "473b2c74df924c7d81105aae3ca6b0e1":{
      "scriptId":"u93"},
    "3cd85e97bef54684951b715044dadc38":{
      "scriptId":"u94"},
    "75aead4644e647a9a8bb3c24169fc702":{
      "scriptId":"u95"},
    "14d5326a9eb64820b75f6d6098de0b7a":{
      "scriptId":"u96"},
    "dd43b5b2556f42d28312faeccac640c3":{
      "scriptId":"u97"},
    "1c1122920e9a434b9b10ac15c58bf843":{
      "scriptId":"u98"},
    "689031384b34422e9eb241a8a27c1900":{
      "scriptId":"u99"},
    "3e489e23101c44c5be7666570951f648":{
      "scriptId":"u100"},
    "2eac595630ab48ce8617b891384f1d12":{
      "scriptId":"u101"},
    "507fb6a1f68c4dc885c9b7b85b6df428":{
      "scriptId":"u102"},
    "1c8560dea7114e72984ad19ef8237cf3":{
      "scriptId":"u103"},
    "9f23abbceafa48589c8d82df26556230":{
      "scriptId":"u104"},
    "571b04e95ae94ba9bb72464c42a8fe7a":{
      "scriptId":"u105"},
    "9c0e951241744ebd9836e33ebcb3fbff":{
      "scriptId":"u106"},
    "87d3748b8937444dbebfd4efe493b822":{
      "scriptId":"u107"},
    "2e14bc74319d49b986ef8e267f4de982":{
      "scriptId":"u108"},
    "221cdc5ccbf5435f8ae44cd8cce1d65f":{
      "scriptId":"u109"},
    "6f95ce2eb24f409c973e6cac6bf94db7":{
      "scriptId":"u110"}}});